/**
 * GÉNÉRATEUR DU TYPE DU PAQUET — `libs-data.d.ts`.
 *
 * Demandé par kanopi le 2026-08-14, et la demande est juste : j'ai fait de `libs-data.js` une porte
 * officielle en déclarant mes `exports`, et **une porte officielle publie sa forme**. Sans type, ses
 * treize contrôles de types tombaient — l'import JSON portait la forme du catalogue, que TypeScript
 * inférait du fichier, tandis que `LIBS.core` arrivait en `unknown`.
 *
 * ⛔ LE TYPE SE DÉRIVE, IL NE S'ÉCRIT PAS. Kanopi a refusé de le recopier chez lui, et il a eu
 * raison : une surface publiée qu'on recopie diverge en silence — c'est la faute qu'on a passé la
 * journée à retirer chez les runtimes. Ce fichier lit LA DONNÉE et en rend la forme ; il ne peut
 * donc pas décrire autre chose que ce qui est publié.
 *
 * ⚠️ IL N'ÉCRIT RIEN SUR LE DISQUE, exactement comme `libs-bundle.js` et pour la même raison : c'est
 * ce qui rend sa fraîcheur vérifiable. Un générateur qui écrit son propre témoin ne prouve rien.
 * Le script npm redirige sa sortie ; `bundle:check` la compare au fichier enregistré.
 *
 * PROFONDEUR — la descente s'arrête à sept niveaux et rend `Record<string, unknown>` au-delà.
 * Mesuré : aucune des clés que les consommateurs nomment aujourd'hui ne vit plus bas (la plus
 * profonde est `core.schema.channels`, à trois). La borne existe pour qu'un catalogue profond ne
 * fasse pas exploser le fichier, et elle est nommée ici plutôt que devinée à la lecture.
 */
import { LIBS } from './libs-data.js';

const PROFONDEUR_MAX = 7;

/** La forme d'une valeur, telle qu'elle est — jamais telle qu'on l'imagine. */
function forme(v, profondeur = 0) {
  if (v === null) return 'null';
  if (Array.isArray(v)) {
    if (!v.length) return 'never[]';
    const membres = [...new Set(v.map((x) => forme(x, profondeur + 1)))];
    return membres.length === 1 ? `${membres[0]}[]` : `(${membres.join(' | ')})[]`;
  }
  if (typeof v === 'object') {
    if (profondeur >= PROFONDEUR_MAX) return 'Record<string, unknown>';
    const cles = Object.keys(v);
    if (!cles.length) return 'Record<string, never>';
    return `{ ${cles.map((k) => `${JSON.stringify(k)}: ${forme(v[k], profondeur + 1)}`).join('; ')} }`;
  }
  if (typeof v === 'number') return 'number';
  if (typeof v === 'boolean') return 'boolean';
  return 'string';
}

const lignes = [
  '// Auto-generated by libs-types.js — do not edit',
  '// La forme des librairies que le paquet publie, DÉRIVÉE de leur contenu.',
  '',
  'export declare const LIBS: {',
  ...Object.entries(LIBS).map(([nom, lib]) => `  ${JSON.stringify(nom)}: ${forme(lib, 1)};`),
  '};',
  '',
];
process.stdout.write(lignes.join('\n'));
