// AUTORITÉ résolution acteur / pitch / contrôles : LIRE src/transpiler/_AUTORITE.md avant de modifier.
/**
 * BPScript Library Loader
 *
 * Loads lib/*.json files based on @ directives in the source.
 * Convention: @file → lib/file.json
 *             @file.key → lib/file.json → entry "key"
 *             @file.key:runtime → load + bind to runtime
 *
 * Browser-compatible BY CONSTRUCTION: this module does NO filesystem access and
 * NO top-level await. Every lib is pre-bundled as plain JS objects in libs-data.js
 * (generated by libs-bundle.js from lib/*.json) and auto-registered below — so the
 * exact same import chain loads in Node AND under a browser bundler (Vite/esbuild).
 * No `node:`/`fs` anywhere in the public import graph. Host code can still add or
 * override libs with registerLib()/registerAll().
 *
 * ⚠ After editing any lib/*.json, regenerate the bundle:
 *     node src/transpiler/libs-bundle.js > src/transpiler/libs-data.js
 */

import { LIBS as BUNDLED_LIBS } from './libs-data.js';

// Registry: pre-loaded libs (browser or Node pre-registration)
const registry = {};

// Cache loaded libs (from filesystem or registry)
const cache = {};

/**
 * Register a single lib by name (e.g. "controls" → contents of lib/controls.json).
 */
function registerLib(name, data) {
  registry[name] = data;
  cache[name] = data;  // also populate cache
  _universeControls = null;  // le registre a bougé → recalculer l'univers
  _universeComponentControls = null;
  _universeRuleScope = null;
  _universeRuleAllowed = null;
  _universeSacs = null;
  _universeIntervalControls = null;
  _universeCompositeControls = null;
  _universeAddressKeys = null;
}

/**
 * Register multiple libs at once.
 * @param {Object} libs - { name: data, ... }
 */
function registerAll(libs) {
  for (const [name, data] of Object.entries(libs)) {
    registerLib(name, data);
  }
}

/**
 * Clear all registered libs and cache (for testing).
 */
function clearRegistry() {
  for (const k of Object.keys(registry)) delete registry[k];
  for (const k of Object.keys(cache)) delete cache[k];
  _universeControls = null;
  _universeComponentControls = null;
  _universeRuleScope = null;
  _universeRuleAllowed = null;
  _universeSacs = null;
  _universeIntervalControls = null;
  _universeCompositeControls = null;
  _universeAddressKeys = null;
}

/**
 * Noms de contrôles de l'UNIVERS — toutes les libs du registre (built-in + user), et non les
 * seules libs que la scène a chargées via ses directives. Sert au garde des clés `[]` : un
 * `[rotate:2]` est une clé CONNUE du langage même dans une scène qui ne déclare pas `@controls`.
 * (Savoir si `@controls` doit être exigé pour l'employer est une question de surface, non tranchée.)
 */
let _universeControls = null;
function universeControlNames() {
  if (!_universeControls) {
    const allDirs = Object.keys(registry).map((name) => ({ name }));
    _universeControls = loadLibsFromDirectives(allDirs).controlNames;
  }
  return _universeControls;
}

// Contrôles interval-typés de l'UNIVERS (marqués `argType:"interval"` dans une lib). Sert au parseur
// AVANT que le libCtx de la scène soit chargé : une directive globale `@transpose:-2400c` doit lire
// une valeur d'INTERVALLE (chaîne brute) dès l'analyse des directives, avant tout consommateur.
let _universeIntervalControls = null;
function universeIntervalControls() {
  if (!_universeIntervalControls) {
    const allDirs = Object.keys(registry).map((name) => ({ name }));
    _universeIntervalControls = loadLibsFromDirectives(allDirs).intervalControls;
  }
  return _universeIntervalControls;
}

// Contrôles à valeur COMPOSITE de l'UNIVERS (marqués `argType:"composite"`). Même besoin que les
// interval-typés : le parseur doit savoir AVANT le libCtx de la scène que la virgule de
// `keyxpand:C4,2` appartient à la VALEUR et ne sépare pas deux arguments.
let _universeCompositeControls = null;
function universeCompositeControls() {
  if (!_universeCompositeControls) {
    const allDirs = Object.keys(registry).map((name) => ({ name }));
    _universeCompositeControls = loadLibsFromDirectives(allDirs).compositeControls;
  }
  return _universeCompositeControls;
}

// Univers des contrôles désignés par un NUMÉRO DE COMPOSANT (`cc.98:45`). Même mécanisme que
// les deux ci-dessus : la donnée déclare, le code ne nomme aucun contrôle.
let _universeComponentControls = null;
function universeComponentControls() {
  if (!_universeComponentControls) {
    const allDirs = Object.keys(registry).map((name) => ({ name }));
    _universeComponentControls = loadLibsFromDirectives(allDirs).componentControls;
  }
  return _universeComponentControls;
}

// Univers des CLÉS D'ADRESSE — elles vivent dans la librairie du canal qui les porte (`midi`
// depuis le 2026-08-15, décision Romain), et le parseur les lit AVANT que le libCtx de la scène
// soit chargé : `E4(ch:5)` doit se ranger dans le tiroir adresse dès l'analyse, quelle que soit
// l'invocation de la scène. Même mécanisme que les univers ci-dessus — la donnée déclare.
let _universeAddressKeys = null;
function universeAddressKeys() {
  if (!_universeAddressKeys) {
    const allDirs = Object.keys(registry).map((name) => ({ name }));
    _universeAddressKeys = loadLibsFromDirectives(allDirs).addressKeys;
  }
  return _universeAddressKeys;
}

// Univers des SACS — quel contrôle s'écrit entre crochets, lequel entre parenthèses. La donnée
// le déclare par sa STRUCTURE (section `engine` contre section `runtime.*`), pas par un champ.
let _universeSacs = null;
function universeSacs() {
  if (!_universeSacs) {
    const allDirs = Object.keys(registry).map((name) => ({ name }));
    const c = loadLibsFromDirectives(allDirs);
    // `specs` : la déclaration COMPLÈTE (args, values, range…) de l'UNIVERS, indépendante de
    // `@controls` — un réglage réservé (qualifierKeys) est un mot du LANGAGE, il doit savoir
    // combien de PARTIES sa valeur porte (`goto`/`failed` : 2 ; `weight`/`rotate`… : 1) que la
    // scène ait chargé `@controls` ou non. Même principe que les univers ci-dessus.
    _universeSacs = { moteur: c.engineBagControls, runtime: c.runtimeBagControls, specs: c.controls };
  }
  return _universeSacs;
}

// Univers des PROCÉDURES DE NIVEAU RÈGLE (`scope:"rule"`). La nature vient de la DONNÉE : le
// parseur ne connaît aucun nom de procédure, il lit le registre.
let _universeRuleScope = null;
function universeRuleScopeControls() {
  if (!_universeRuleScope) {
    const allDirs = Object.keys(registry).map((name) => ({ name }));
    _universeRuleScope = loadLibsFromDirectives(allDirs).ruleScopeControls;
  }
  return _universeRuleScope;
}

// Univers des contrôles dont la portée déclarée INCLUT la règle.
let _universeRuleAllowed = null;
function universeRuleAllowedControls() {
  if (!_universeRuleAllowed) {
    const allDirs = Object.keys(registry).map((name) => ({ name }));
    _universeRuleAllowed = loadLibsFromDirectives(allDirs).ruleAllowedControls;
  }
  return _universeRuleAllowed;
}

// Auto-register the pre-bundled libs at module load (Node AND browser).
// This replaces the former Node-only `fs` fallback: the registry is always
// populated from libs-data.js, so loadJsonFile never needs the filesystem.
registerAll(BUNDLED_LIBS);

// Canonical filenames (directive name → JSON file name)
// `tuning` → tunings.json = le CATALOGUE servi (PITCH_LIB). Avant cet alias,
// loadLib('tuning', X) tombait sur lib/tuning.json (héritage Bernard, gammes sous
// .scales) et ne résolvait JAMAIS rien — la résolution d'accordage était 100 %
// aval (Kairos). L'alias ouvre l'accès transpileur au catalogue (SCENE_VALUES).
// `scale` → scales.json : axe-composant à catalogue (domain:scale) promu au CUTOVER universel
// (Romain 2026-07-14, tour [412]) — ouvre l'accès transpileur pour valider `@scale.<nom>`.
const fileAliases = { alphabet: 'alphabets', tuning: 'tunings', scale: 'scales', sound: 'sounds' };

/**
 * L'axe nommé dans une invocation → le FICHIER qui le sert. Exporté parce que l'adresse produite
 * porte l'AXE (`sound.tabla_perc`) alors que la donnée vit sous le nom du FICHIER (`sounds`) :
 * qui veut remonter d'une adresse à sa librairie doit passer par ici. Recopier la table ailleurs
 * rouvrirait l'écart entre ce qu'on invoque et ce qu'on charge.
 */
function fichierDeLAxe(axe) {
  return fileAliases[axe] || axe;
}

function loadJsonFile(name) {
  const canonical = fileAliases[name] || name;
  if (cache[canonical]) return cache[canonical];

  // Try registry first (canonical then original name)
  const regData = registry[canonical] || registry[name];
  if (regData) {
    cache[canonical] = regData;
    return regData;
  }

  return null;
}

/**
 * Load a lib by name, with optional subkey.
 * @file → lib/file.json (whole file)
 * @file.subkey → lib/file.json → entry from the top-level collection
 *
 * For alphabets.json: the collection key is "alphabets"
 * For sub.json: the collection key is "tables"
 * Generic fallback: tries the subkey directly on the root object
 */
function loadLib(name, subkey) {
  if (subkey) {
    const file = loadJsonFile(name);
    if (file) {
      // Look for subkey in known collection fields, or directly on root.
      // `objects` AJOUTÉ le 2026-08-06 : c'est le champ que les librairies de CODE emploient
      // (`mod.json`, `voices.json`, et `eval.json` depuis la décision Romain du jour). Sans lui,
      // une entrée de ces librairies était INATTEIGNABLE par `loadLib(axe, entrée)` — la donnée
      // existait, le chargeur regardait ailleurs et rendait `null`.
      const entry = file.alphabets?.[subkey] || file.tables?.[subkey] || file.objects?.[subkey]
                 || file[subkey];
      if (entry) return entry;
    }
    // Fallback: try name/subkey as a separate file (e.g. settings/visser2.json)
    const subFile = loadJsonFile(name + '/' + subkey);
    if (subFile) return subFile;
    return null;
  }

  // No subkey — load the whole file
  return loadJsonFile(name);
}

/**
 * LA LIBRAIRIE `L` DÉCLARE-T-ELLE LA DIRECTIVE `nom` ? — lue dans la DONNÉE, jamais en dur.
 *
 * POURQUOI ELLE EXISTE. `loadLib(L, nom)` répond à une autre question : il cherche une ENTRÉE de
 * catalogue (`@alphabet.sargam`), donc dans `alphabets`/`tables`/`objects`/racine. Une DIRECTIVE
 * ne vit dans aucun de ces champs — `tempo` est déclaré dans `time.schema.reservedDirectives` —
 * si bien que `@core.tempo:120` était refusé par le message « l'entrée n'existe pas dans la
 * librairie » alors que la librairie la déclare bel et bien, deux champs plus loin.
 *
 * CE QUE ROMAIN A TRANCHÉ (2026-08-09) : le préfixe est OPTIONNEL, il n'a jamais été INTERDIT, et
 * il vaut pour TOUTE paire librairie.directive — pas pour le seul tempo. C'est la contrepartie
 * exacte de la résolution par unicité du 2026-08-02 : le nom nu marche quand il est unique, le
 * préfixe nomme explicitement qui le déclare. La bible l'écrivait déjà (« le préfixe reste
 * écrivable partout, y compris là où un nom nu suffirait ») ; il n'était écrivable nulle part.
 *
 * ⚠️ SUIT LA CHAÎNE `apporte`, TRANSITIVEMENT (2026-08-10, mise en conformité des librairies).
 * `@core` amène `engine` (lib/core.json `apporte`) : `@core.seed:42` doit donc rester une
 * écriture valide de `@seed:42` MÊME MAINTENANT QUE `seed` a déménagé dans `lib/engine.json` —
 * le préfixe nomme le POINT D'ENTRÉE que l'auteur invoque, pas forcément le domicile final de la
 * clé. TRANSITIF depuis la scission de `controls.json` : `core` amène `controls`, qui amène à
 * son tour `expression`/`midi`/`audio`/`transpo` — `@core.transpose:2` doit rester valide à
 * DEUX maillons de distance. `vus` protège d'un cycle d'`apporte` mal formé.
 */
/**
 * LES PORTÉES DÉCLARÉES d'un mot, cherchées dans TOUTES les librairies du registre et dans TOUTES
 * leurs sections — ou `null` si aucune ne le déclare.
 *
 * ⚠️ LA PORTÉE FAIT FOI, PAS LA SECTION OÙ LE MOT EST RANGÉ. Le même principe tient déjà la
 * reconnaissance des mots de tête (voir `loadLibsFromDirectives`) : un mot rangé sous `subgrammar`
 * mais portant `scope:["scene"]` s'écrit en tête, et l'inverse est vrai aussi. Chercher par section
 * reviendrait à faire dire à un classement ce que la donnée dit déjà.
 *
 * Sert au parseur là où une POSITION doit être validée — les modificateurs de sous-grammaire, qui
 * n'étaient confrontés à rien avant le 2026-08-10.
 */
function porteesDeclarees(nom) {
  if (!nom) return null;
  for (const lib of Object.values(registry)) {
    if (!lib || typeof lib !== 'object') continue;
    const res = lib.schema && lib.schema.reservedDirectives;
    if (res && !Array.isArray(res) && res[nom] && Array.isArray(res[nom].scope)) return res[nom].scope;
    for (const section of Object.values(lib)) {
      if (!section || typeof section !== 'object' || Array.isArray(section)) continue;
      const def = section[nom];
      if (def && typeof def === 'object' && Array.isArray(def.scope)) return def.scope;
    }
  }
  return null;
}

/**
 * LE GROUPE D'UNICITÉ d'un mot — le nom du réglage qu'il pose, quand ce réglage ne se pose qu'une
 * fois par scène — ou `null`. Cherché dans TOUTES les librairies et TOUTES leurs sections, comme
 * les portées : la section range, la donnée déclare.
 *
 * ⚠️ UN GROUPE, PAS UN BOOLÉEN, et c'est le moteur qui l'impose : `_striated` et `_smooth` partagent
 * un seul compteur (`NotFoundNatureTime`, CompileGrammar.c:1545) parce qu'ils règlent la MÊME chose.
 * Un `unique:true` par mot aurait laissé passer l'un suivi de l'autre.
 */
function groupeDUnicite(nom) {
  if (!nom) return null;
  for (const lib of Object.values(registry)) {
    if (!lib || typeof lib !== 'object') continue;
    const res = lib.schema && lib.schema.reservedDirectives;
    if (res && !Array.isArray(res) && res[nom] && res[nom].unicite) return res[nom].unicite;
    for (const section of Object.values(lib)) {
      if (!section || typeof section !== 'object' || Array.isArray(section)) continue;
      const def = section[nom];
      if (def && typeof def === 'object' && def.unicite) return def.unicite;
    }
  }
  return null;
}

function directiveDeclareeParLaLibrairie(lib, nom) {
  const file = loadJsonFile(lib);
  if (!file || !nom) return false;
  const declareeIci = (f) => {
    if (!f) return false;
    // `reservedDirectives` porte DEUX formes légitimes — array plat (core.json) ou objet
    // {nom: {description, scope}} (engine.json, time.json, depuis 2026-08-10). Les deux se
    // consultent par présence du nom, jamais recopiées l'une dans l'autre.
    const reserved = (f.schema && f.schema.reservedDirectives) || [];
    if (Array.isArray(reserved) && reserved.includes(nom)) return true;
    if (!Array.isArray(reserved) && Object.prototype.hasOwnProperty.call(reserved, nom)) return true;
    if (f.values && Object.prototype.hasOwnProperty.call(f.values, nom)) return true;
    if (f.controls && Object.prototype.hasOwnProperty.call(f.controls, nom)) return true;
    return false;
  };
  if (declareeIci(file)) return true;
  const vus = new Set([lib]);
  const aTraiter = Array.isArray(file.apporte) ? [...file.apporte] : [];
  while (aTraiter.length) {
    const nomLib = aTraiter.shift();
    if (vus.has(nomLib)) continue;
    vus.add(nomLib);
    const f = loadJsonFile(nomLib);
    if (declareeIci(f)) return true;
    if (f && Array.isArray(f.apporte)) aTraiter.push(...f.apporte);
  }
  return false;
}

/**
 * Résout un alphabet nommé pour une LIAISON D'ACTEUR (`@actor X @alphabet.<nom>`).
 *
 * POURQUOI CETTE FONCTION EXISTE. `loadLib('alphabet', nom)` ne connaît QUE le catalogue standard
 * (`alphabets.json`). Or une scène peut déclarer d'autres librairies d'alphabets — `@test_alphabets`
 * en est une — et leurs entrées étaient alors INATTEIGNABLES depuis un acteur : la scène savait les
 * résoudre, l'acteur non. `tryKeyMap` est tombé exactement là (terminaux `a`/`b` de
 * `test_alphabets.abc`, inatteignables une fois passés par un acteur).
 *
 * On ne DUPLIQUE pas ces entrées dans `alphabets.json` : une donnée en deux exemplaires est
 * précisément le défaut qu'on élimine. On élargit la RÉSOLUTION, pas le catalogue.
 *
 * Ordre : le catalogue standard d'abord (il fait autorité), puis les librairies que la scène a
 * elle-même déclarées, dans leur ordre de déclaration. Rend `null` si rien ne porte ce nom.
 */
function resolveActorAlphabet(nom, directives) {
  const r = resolveActorAlphabetSource(nom, directives);
  return r ? r.entry : null;
}

/**
 * Même résolution, mais elle rend AUSSI le fichier d'où l'entrée provient (`lib`) —
 * `null` quand c'est le catalogue standard.
 *
 * POURQUOI CETTE VARIANTE. `resolveActorAlphabet` répond « cet alphabet existe-t-il », ce qui
 * suffit à résoudre et à valider. Elle ne répond PAS à « d'où vient-il », et c'est précisément
 * ce que l'aval doit savoir : Kairos lit le domaine DÉCLARÉ DANS LE FICHIER et n'invente rien
 * (contrat bpx-kairos-arbre §2.1). Un nom nu comme `abc` ne dit pas son fichier — l'adresse
 * canonique `test_alphabets.abc`, si. Les deux fonctions posent donc la même question au même
 * endroit : dupliquer la recherche ici serait rouvrir l'écart entre validation et résolution.
 */
function resolveActorAlphabetSource(nom, directives) {
  const standard = loadLib('alphabet', nom);
  if (standard && nomsDeTerminaux(standard)) return { entry: standard, lib: null };
  for (const d of directives || []) {
    if (!d || !d.name || d.name === 'alphabet') continue;
    const entry = loadLib(d.name, nom);
    if (entry && nomsDeTerminaux(entry)) return { entry, lib: d.name };
  }
  return null;
}

/**
 * Load all libraries referenced by @ directives in the AST.
 * Returns a merged context: { controls, controlMap, noArgControls, symbols }
 */
/**
 * LA FORME d'une déclaration de contrôle — liste BLANCHE de la frontière donnée → langage.
 *
 * Les 57 contrôles du dépôt portent TOUS `args` et `description` : la mesure fixe le critère, on
 * ne l'a pas choisi. Exiger la forme plutôt qu'exclure des noms de clés est ce qui empêche la
 * prochaine clé de commodité d'entrer au vocabulaire sans être remarquée.
 */
function estUneDeclarationDeControle(def) {
  return def !== null && typeof def === 'object' && !Array.isArray(def)
      && 'args' in def && 'description' in def;
}

/**
 * LES NOMS DE TERMINAUX D'UN ALPHABET — un seul accès, pour tout le dépôt.
 *
 * ⚠️ POURQUOI UNE FONCTION ET NON DOUZE LECTURES. Le format des alphabets a été reformaté le
 * 2026-08-08 sur le prototype de `LANGUAGE.md` : la liste `notes` est devenue la collection
 * `terminals`, où chaque terminal porte ses clés — « un terminal est une chose entière »
 * (décision Romain, 2026-08-01). DOUZE sites lisaient `.notes` en dur ; les remplacer un par un
 * aurait laissé le prochain changement casser aux douze mêmes endroits, et il aurait fallu les
 * retrouver. Un seul accès, et le format ne se lit plus qu'ici.
 */
function nomsDeTerminaux(alphabetLib) {
  if (!alphabetLib || !alphabetLib.terminals || typeof alphabetLib.terminals !== 'object') return null;
  return Object.keys(alphabetLib.terminals);
}

function loadLibsFromDirectives(directives) {
  const ctx = {
    controls: {},       // name → { bp3, args, ... }
    controlMap: {},     // name → bp3 name (e.g. "vel" → "_vel")
    // ⛔ LE DESTINATAIRE D'UN CONTRÔLE — nom → l'outil qui le RÉSOUT, verbatim depuis le champ
    // `resolvedBy` de la librairie qui le déclare. C'est le principe de découpage des librairies
    // (une librairie, un destinataire) rendu LISIBLE : sans cette table, l'information s'arrêtait
    // au chargeur et l'aval devait redeviner la destination à partir du nom de la clé, avec une
    // table recopiée chez lui — qui dérive en silence le jour où une clé change de librairie.
    // La valeur n'est jamais traduite ni interprétée ici : elle est portée telle qu'elle est
    // écrite, et c'est le consommateur qui sait ce qu'il en fait.
    controlResolvedBy: {},
    // `<librairie>.<contrôle>` → la déclaration, pour lever l'ambiguïté quand deux librairies
    // portent le même nom (règle Romain 2026-08-13). Toujours peuplé, ambiguïté ou non : la forme
    // préfixée s'écrit et se lit dans les deux cas, elle n'est pas un mode de secours.
    controlsQualified: {},
    controlQualifiedResolvedBy: {},
    // Les noms qu'au moins DEUX librairies déclarent — écrits nus, ils sont refusés.
    ambiguousControls: new Set(),
    // ── L'INTERFACE ET SA RÉALISATION ────────────────────────────────────────────────────────
    // `<librairie>.<contrôle>` de l'INTERFACE → les qualifiés qui la RÉALISENT. Doctrine de
    // Romain : « MIDI a toutes ses primitives, et `expression` est un sur-ensemble d'appel
    // générique qui va appeler les primitives d'expression du runtime sous-jacent quel qu'il
    // soit ». Un mot déclaré des deux côtés n'est donc pas une paire d'homonymes : il y a UNE
    // entrée publique — l'interface — et des réalisations qu'on vise par leur préfixe.
    implementations: {},
    // Le qualifié de la réalisation → le qualifié de l'interface qu'elle réalise (l'inverse).
    implementedInterface: {},
    controlNames: new Set(),
    bp3NativeControls: new Set(),  // controls BP3 understands natively (no "transport" field)
    seqPrefixControls: new Set(),  // engine controls with scope:"seq_prefix" — emitted as prefix inside group/sequence
    dispatcherOnlyControls: new Set(),  // controls only the dispatcher understands (have "transport" field, e.g. audio)
    dualContextControls: new Set(),  // controls that appear in BOTH engine and runtime — in () always route to _script
    subgrammarControls: new Map(),  // subgrammar-level directives: name → { bp3, args }
    noArgControls: new Set(),
    bagOnlyControls: new Set(),  // `bagOnly:true` — aucune forme nue dans le flux, cf. plus bas
    compositeControls: new Set(),  // controls whose value is COMPOSITE (`pivot,facteur`) : la
                                   // virgule appartient à la VALEUR, portée brute en une seule chaîne.
    // ⛔ CES DEUX ENSEMBLES DISENT LE DESTINATAIRE, PAS LE SIGNE (rectifié 2026-08-08, Romain :
    // « le destinataire des contrôles est spécifié dans la LIBRAIRIE dans laquelle le contrôle est
    // listé, c'est la seule source de vérité »). Leur ancien commentaire — « déclarés sous `engine`
    // → sac MOTEUR `[…]` » — faisait dire à la librairie COMMENT une chose s'écrit alors qu'elle ne
    // répond qu'à QUI l'exécute. C'est cette confusion qui a fait croire qu'un contrôle exécuté par
    // le moteur devait s'écrire entre crochets : `shuffle`, `retro` et `order` sont bien moteur, et
    // s'écrivent entre PARENTHÈSES parce qu'ils manipulent ce qui est produit.
    // Le SIGNE dit ce que la chose EST — dérivation ou production. Chantier en cours.
    engineBagControls: new Set(),   // exécutés par le MOTEUR (déclarés sous `engine`)
    runtimeBagControls: new Set(),  // exécutés par le RUNTIME (déclarés sous `runtime.*`)
                                    // Un contrôle ne vit pas dans les deux.
    ruleAllowedControls: new Set(), // portée INCLUANT `rule` — voir le commentaire du remplissage
    ruleScopeControls: new Set(),  // PROCÉDURES DE NIVEAU RÈGLE (`scope:"rule"` dans la lib) :
                                   // goto, failed, repeat, stop. Elles ne s'appliquent pas à une
                                   // POSITION mais à la RÈGLE entière — le moteur les extrait en
                                   // métadonnée (BPx loadGrammar.ts:3996 mergeQualifierProcedures).
    componentControls: new Set(),  // contrôles désignés par un NUMÉRO DE COMPOSANT : `(cc.98:45)`.
                                   // Marqués `component:"number"` dans la lib. Le point appelle le
                                   // composant, les deux points affectent la valeur.
    intervalControls: new Set(),  // controls whose argument is a MUSICAL INTERVAL (fraction 3/2, cents 700c,
                                  // decimal 1.5) — marqués `argType:"interval"` dans la lib. La valeur est
                                  // portée BRUTE (chaîne) et résolue en aval par normalizeRatio (Kairos).
    symbols: {},        // name → { type, ... }
    alphabetTerminals: [],  // terminaux issus des SEULS alphabets (sans @core etc.) —
                            // porte du découpeur mono-char (bpxAst.js, flip Palier 4 étape A)
    cvObjects: {},      // "lib.type" → def (e.g. "mod.adsr" → { parameters, ... })
    _libs: {},          // directive name → raw lib data (for generator access)
    _alphabets: [],     // loaded alphabet libs (deferred terminal generation)
    _octaveConvention: null,  // resolved octave convention name
    transcriptions: {},  // name → { mappings: { a: b, ... } }
    // SCENE_VALUES (hub [293]) : registre GÉNÉRIQUE des valeurs déclarées par les
    // librairies chargées (section top-level `values` d'un fichier lib). Une valeur
    // ajoutée demain à une lib = une entrée JSON, zéro code. nom → spec
    // { unit?, range?, values?, default?, componentDefault?, description?, _axis }.
    // `_axis` = clé d'entité d'acteur du fichier déclarant (tuning, alphabet…) —
    // sert à résoudre `componentDefault` sur le composant référencé par l'acteur.
    valueRegistry: {},
    valueRegistryErrors: [],  // collisions de noms (réservés/contrôles) — remontées à l'émission
  };

  // SOCLE @core + SCHÉMA du langage — chargés en DONNÉE, plus aucune liste en dur (Romain
  // 2026-07-05, prépare user libraries + partage du vocabulaire à Kanopi). @core.schema
  // déclare : `reservedDirectives` (mots de directive du langage, non-valeurs), `catalogAxes`
  // (axes dont les valeurs sont des entrées de catalogue). @core.defaults porte les
  // valeurs/composants par défaut (cascade). Les CLÉS D'ADRESSE ont quitté le socle le
  // 2026-08-15 : elles vivent chez le canal qui les porte, et se lisent en union du registre.
  const coreLib = loadJsonFile('core') || {};
  const schema = coreLib.schema || {};
  // ⚠️ `reservedDirectives` PORTE DEUX FORMES, ET LES DEUX SONT LÉGITIMES (2026-08-10) : `core.json`
  // le garde en LISTE PLATE (noms seuls — ses ~30 clés d'axe/tombstone n'ont pas encore de scope
  // mesuré) ; `engine.json`/`time.json` le portent en OBJET `{nom: {description, scope}}` (chaque
  // clé y porte sa portée, exigé par Romain). `nomsReserves` lit les deux sans en préférer une.
  const nomsReserves = (rd) => (Array.isArray(rd) ? rd : Object.keys(rd || {}));
  // UNION sur TOUTES les librairies du REGISTRE, pas seulement `core` — sinon une clé qui ne vit
  // QUE dans `engine`/`time` (mode, seed, tempo…) redevient « inconnue » en forme nue dès que
  // `core.json` ne la duplique plus (2026-08-10, solde des 15 collisions core/engine : une clé ne
  // vit que dans UNE librairie). Conforme à LIBRAIRIES.md:34 : « les catégories du cœur s'invoquent
  // directement, sans nommer la librairie qui les porte » — donc TOUJOURS résolues, quelle que soit
  // l'invocation de la scène, comme `core` l'était déjà seul avant ce chantier.
  ctx.reservedDirectiveNames = new Set(nomsReserves(schema.reservedDirectives));
  ctx.addressKeys = new Set();
  for (const lib of Object.values(registry)) {
    const s = lib && lib.schema;
    if (s && s.reservedDirectives) for (const n of nomsReserves(s.reservedDirectives)) ctx.reservedDirectiveNames.add(n);
    // ── LES CLÉS D'ADRESSE VIVENT CHEZ LE CANAL QUI LES PORTE ────────────────────────────────
    // Décision de Romain (2026-08-15) : `ch`, `channel`, `device`, `port` et `note` quittent le
    // socle pour `midi`. Le destinataire cesse donc d'être écrit dans une légende du schéma — il
    // se lit sur le `resolvedBy` de la librairie qui les déclare, comme pour tout le reste.
    // Même UNION que les directives réservées, et pour la même raison : une clé qui ne vit que
    // dans `midi` doit rester résolue quelle que soit l'invocation de la scène.
    if (s && s.addressKeys) for (const n of nomsReserves(s.addressKeys)) ctx.addressKeys.add(n);
    // ⚠️ ET LA PORTÉE FAIT FOI, PAS LA SECTION OÙ LE MOT EST RANGÉ. Règle 3 de Romain : « tous les
    // contrôles acceptés AVEC LEURS PORTÉES sont définis dans les librairies uniquement ». Un
    // contrôle qui déclare `scope` contenant `scene` s'écrit donc en tête, et doit y être reconnu.
    //
    // MESURÉ le 2026-08-10 : `striated` et `smooth` portent `scope:["subgrammar","scene"]` dans la
    // section `subgrammar` de `engine`, et restaient INCONNUS en tête — 24 sources du corpus les
    // écrivent. Les recopier dans `schema.reservedDirectives` aurait fait DEUX domiciles pour un
    // nom ; c'est la résolution qui devait apprendre à lire la portée.
    for (const section of Object.values(lib || {})) {
      if (!section || typeof section !== 'object' || Array.isArray(section)) continue;
      for (const [nom, def] of Object.entries(section)) {
        if (nom.startsWith('_') || !def || typeof def !== 'object') continue;
        if (Array.isArray(def.scope) && def.scope.includes('scene')) ctx.reservedDirectiveNames.add(nom);
      }
    }
  }
  // Clés réservées de `[]` (docs/spec/LANGUAGE.md §« Clés reservees de [] ») : elles ne sont
  // pas des contrôles de librairie, le compilateur les comprend lui-même. Toute autre clé
  // dans `[]` est une erreur de compilation (ibid.) — cf. checkQualifierKey() du parser.
  ctx.qualifierKeys = new Set(schema.qualifierKeys || []);
  ctx.catalogAxes = Array.isArray(schema.catalogAxes) ? schema.catalogAxes.slice() : [];
  ctx.defaultComponents = (coreLib.defaults && coreLib.defaults.components) || {};

  const mergeValueRegistry = (file, axis) => {
    if (!file || !file.values || typeof file.values !== 'object') return;
    for (const [vname, spec] of Object.entries(file.values)) {
      if (vname.startsWith('_') || !spec || typeof spec !== 'object') continue;
      if (ctx.reservedDirectiveNames.has(vname) || ctx.controlNames.has(vname)) {
        ctx.valueRegistryErrors.push({
          message: `Valeur de librairie '${vname}' : nom réservé (directive moteur ou contrôle existant) — renommer dans la librairie`,
        });
        continue;
      }
      ctx.valueRegistry[vname] = { ...spec, _axis: axis || null };
    }
  };

  // @core.defaults.values : valeurs socle (diapason…) au registre (le nom `diapason` est
  // dans reservedDirectives pour bloquer une collision de lib, mais le socle @core le pose ici).
  if (coreLib.defaults && coreLib.defaults.values) {
    for (const [vname, spec] of Object.entries(coreLib.defaults.values)) {
      if (vname.startsWith('_') || !spec || typeof spec !== 'object') continue;
      ctx.valueRegistry[vname] = { ...spec, _axis: null };
    }
  }

  // Fonctions DIGITALES/dispatcher (transpose, rotate, keyxpand…) — toujours disponibles,
  // indépendantes de @controls. Source : digital.json (générique — une fonction ajoutée = reconnue).
  const digitalLib = loadJsonFile('digital');
  ctx.digitalFunctions = new Set(Object.keys((digitalLib && digitalLib.objects) || {}));

  // Always load settings (engine defaults)
  const settingsLib = loadLib('settings');
  if (settingsLib) ctx._libs['settings'] = settingsLib;

  // Registre des ENTRÉES DE MODULATION par type de sortie (lib/modulation.json) — toujours
  // disponible (intrinsèque, pas besoin de @modulation). Utilisé pour valider les noms écrits
  // au point de branchement `(cutoff: env1)`. modulationInputs : { type → Set(noms) } ;
  // modulationInputsAll : union de tous les noms (fallback quand le type de sortie n'est pas résolu).
  ctx.modulationInputs = {};
  ctx.modulationInputsAll = new Set();
  const modulationLib = loadLib('modulation');
  if (modulationLib) {
    for (const [type, inputs] of Object.entries(modulationLib)) {
      if (type.startsWith('_') || !inputs || typeof inputs !== 'object') continue;
      const set = new Set(Object.keys(inputs));
      ctx.modulationInputs[type] = set;
      for (const n of set) ctx.modulationInputsAll.add(n);
    }
    ctx._libs['modulation'] = modulationLib;
  }

  // ⛔ `cc` ET `sound` SUPPRIMES le 2026-08-08 (Romain :  on supprime les deux controles et le
  // code correspondant ). Ils etaient AJOUTES ICI, en JavaScript, au lieu d etre declares dans une
  // librairie -- ils echappaient donc a tout ce que la donnee impose : aucune portee, aucun
  // destinataire lisible, et AUCUN GARDE ne les voyait. C est ce qui laissait `sound` passer entre
  // crochets alors que rien ne l y autorisait.
  // Mesure au moteur natif avant de trancher : ni l un ni l autre n existe en BP3 -- aucun
  // `_sound`, et la plomberie MIDI du moteur ne porte aucun controle de grammaire `_cc`. Les deux
  // etaient des inventions BPScript.
  // Un controle se declare desormais dans la librairie de son destinataire, sans exception.

  // ⛔ INVOQUER COMMANDE — SYSTÉMATIQUEMENT (Romain, 2026-08-08).
  //
  // « Est-ce qu'invoquer une librairie doit commander ce que le langage accepte ? — La réponse est
  // oui, systématiquement. Et si un mot est inconnu dans le corpus invoqué, alors erreur. »
  // Avec, le même jour : « on a dit qu'on supprimait controls et que core intégrait l'appel à
  // controls, que ça ne servait à rien de tout le temps devoir appeler les deux. »
  //
  // Les deux phrases se tiennent : `@core` AMÈNE les contrôles, donc une scène qui l'écrit en
  // dispose sans les invoquer — et une scène qui n'invoque RIEN n'a rien, un réglage y est refusé.
  // ⚠️ CE N'EST PAS « LES CONTRÔLES SONT TOUJOURS LÀ ». Ma première écriture les chargeait
  // inconditionnellement : elle fermait bien la brèche de l'arbre, mais elle violait la règle
  // ci-dessus — l'invocation ne commandait toujours rien, elle était juste devenue inutile.
  // Le lien vit dans la DONNÉE (`lib/core.json`, champ `apporte`) : ce code ne nomme aucune
  // librairie, et une librairie ajoutée demain au socle est une entrée JSON.
  //
  // LA RÉFÉRENCE ÉTAIT DÉJÀ DE CE CÔTÉ, mesuré le jour même : `@controls` n'apparaît AUCUNE fois
  // dans les trois spécifications (`LANGUAGE.md`, `EBNF.md`, `AST.md`) — `@core` y est écrit
  // quinze fois. C'est le code qui traînait, et rien ne pouvait le dire : aucune décision datée
  // ne portait la suppression, donc aucun garde ne pouvait mordre.
  //
  // ⚠️ CE QUE L'INVOCATION FACULTATIVE COÛTAIT, ET C'EST LE VRAI DÉFAUT. Le même texte produisait
  // DEUX arbres différents selon qu'une ligne de tête était écrite ou non :
  //     `S -> C4(vel:80)` AVEC la ligne  → une NOTE portant un RÉGLAGE
  //     `S -> C4(vel:80)` SANS la ligne  → un APPEL de fonction portant un ARGUMENT
  // Les deux compilaient. L'écriture ne décidait donc pas de ce qu'elle produit — une déclaration
  // trois lignes plus haut décidait à sa place. En aval, BPx cherche les réglages là où il les
  // connaît : sur la seconde forme il ne les trouvait pas, sans erreur, et jouait la note sans son
  // intensité. Même famille que le poids perdu le matin même.
  //
  // ⚠️ ET LE DÉFAUT AVAIT DÉJÀ ÉTÉ PAYÉ UNE FOIS, SUR UNE SEULE FAMILLE. Les quatre contrôles de
  // sous-grammaire (`mm`, `striated`, `smooth`, `destru`) étaient semés ici EN DUR, avec un
  // commentaire qui disait exactement la cause : « silently dropped unless @controls was loaded ».
  // On avait donc réparé l'endroit où le défaut s'était MONTRÉ, pas l'espace où il vivait — et les
  // 61 autres contrôles sont restés dans le trou. La graine en dur disparaît avec ce chargement :
  // la librairie les déclare, plus rien ne les recopie.
  // ⚠️ CHAÎNE TRANSITIVE (2026-08-10, scission de controls.json) : un `apporte` peut désormais
  // en amener un autre — `core` apporte `controls`, qui apporte `expression`/`midi`/`audio`/
  // `transpo`. Une seule passe s'arrêtait au premier maillon : `@core` seul aurait chargé
  // `controls` (qui ne porte plus aucun contrôle, juste sa propre chaîne `apporte`) SANS
  // atteindre les quatre destinataires réels. `invoquees` sert de garde anti-cycle : un nom
  // déjà vu ne se retraite pas, quelle que soit la profondeur d'où il revient.
  const invoquees = new Set((directives || []).map((d) => d && d.name).filter(Boolean));
  const apportees = [];
  const aTraiter = [...(directives || [])];
  while (aTraiter.length) {
    const d = aTraiter.shift();
    const socle = d && d.name ? loadJsonFile(d.name) : null;
    for (const nom of (socle && Array.isArray(socle.apporte) ? socle.apporte : [])) {
      if (invoquees.has(nom)) continue;      // déjà invoquée en propre (ou apportée) : rien à ajouter
      invoquees.add(nom);
      const nouvelle = { type: 'Directive', name: nom, subkey: null };
      apportees.push(nouvelle);
      aTraiter.push(nouvelle);               // sa PROPRE chaîne apporte se résout à son tour
    }
  }
  const aCharger = apportees.length ? [...apportees, ...(directives || [])] : (directives || []);

  // ⛔ DEUX DÉCLARATIONS D'UN MÊME CONTRÔLE SONT PERMISES — ET L'APPEL SE PRÉFIXE ALORS.
  //
  // RÈGLE DE ROMAIN (2026-08-13) : « on peut avoir deux déclarations d'un même contrôle, et à ce
  // moment-là on a l'obligation de l'appeler en préfixant `<nom de la librairie>.<contrôle>` ».
  //
  // CE QUE J'AVAIS ÉCRIT, ET QUI ÉTAIT FAUX : un refus DUR à la déclaration. Le raisonnement se
  // tenait — le destinataire d'un réglage se lit sur la librairie qui le déclare, donc deux
  // déclarations donnent deux destinataires — mais la conclusion était l'inverse de la règle. Ce
  // n'est pas la DÉCLARATION qui est indécidable, c'est l'APPEL NU : `pan` seul, quand deux
  // librairies le déclarent, ne dit pas de quel `pan` on parle. `audio.pan` et `midi.pan` le
  // disent, et ce sont deux contrôles légitimes avec deux destinataires.
  //
  // CE QUI RESTE REFUSÉ, ET C'EST LE VRAI DÉFAUT : le chargeur ne tranche JAMAIS en silence. Une
  // clé ambiguë écrite nue est refusée AVEC SA RÉÉCRITURE, la liste des préfixes possibles.
  // Un choix silencieux ne se voit pas depuis l'aval — le réglage part au mauvais outil sans
  // erreur, et rien ne rougit le jour où une clé change de librairie.
  //
  // LA TOLÉRANCE inchangée : la MÊME section du MÊME fichier peut être reversée deux fois (une
  // directive écrite deux fois dans une scène) ; il n'y a alors ni deux définitions ni deux
  // destinataires, donc aucune ambiguïté à lever.
  const provenance = new Map();   // nom de contrôle → Set des origines `lib/<x>.json → <section>`
  const declarer = (nom, origine) => {
    if (!provenance.has(nom)) provenance.set(nom, new Set());
    provenance.get(nom).add(origine);
  };

  for (const dir of aCharger) {
    // @cc directives: user-defined named CC mappings
    if (dir.name === 'cc' && dir.ccMappings) {
      for (const cc of dir.ccMappings) {
        declarer(cc.name, `le contrôleur nommé '@cc ${cc.name}' de la scène`);
        ctx.controls[cc.name] = {
          args: ['value'], range: [0, 127], default: 0,
          description: `User CC${cc.number}`, transportGroup: 'midi', ccNumber: cc.number
        };
        ctx.controlMap[cc.name] = `_${cc.name}`;
        ctx.controlNames.add(cc.name);
        ctx.dispatcherOnlyControls.add(cc.name);
      }
      continue;
    }

    // SCENE_VALUES : les références d'entité d'un @actor (alphabet/tuning/octaves)
    // touchent leurs fichiers-catalogues → leurs sections `values` entrent au registre
    // (sinon une scène 100 % acteurs n'aurait aucun registre). Le fichier est chargé,
    // pas l'entrée — la résolution du composant reste à l'émission/en aval.
    // (Les acteurs sont hissés par le parseur dans ast.actors — type ActorDirective,
    //  name = nom de l'acteur ; l'émission BPx les inclut dans la liste passée ici.)
    if ((dir.type === 'ActorDirective' || dir.name === 'actor') && dir.properties) {
      for (const axis of ['alphabet', 'tuning', 'octaves']) {
        if (dir.properties[axis]) mergeValueRegistry(loadJsonFile(axis), axis);
      }
      continue;
    }

    const lib = loadLib(dir.name, dir.subkey);
    // Section `values` du FICHIER de la directive (ex. @tuning.X → tunings.json),
    // même si l'entrée subkey n'existe pas (le registre est au niveau fichier).
    mergeValueRegistry(loadJsonFile(dir.name), dir.name);
    if (!lib) continue;
    const libKey = dir.subkey ? `${dir.name}.${dir.subkey}` : dir.name;
    ctx._libs[libKey] = lib;

    // Merge subgrammar-level directives (destru, striated, smooth, mm)
    if (lib.subgrammar) {
      for (const [name, def] of Object.entries(lib.subgrammar)) {
        if (name === '_comment') continue;
        ctx.subgrammarControls.set(name, def);
      }
    }

    // Merge controls — engine (BP3 native) and runtime (dispatcher)
    // Runtime section may contain sub-groups (musical, midi, audio, dispatcher, generic)
    const controlSources = [];
    if (lib.controls) controlSources.push({ source: lib.controls, isEngine: false, section: 'controls' });
    if (lib.engine) controlSources.push({ source: lib.engine, isEngine: true, section: 'engine' });
    // ⛔ LA SECTION `subgrammar` PARTICIPE AUX SACS QUAND SA PORTÉE DÉCLARE LE FLUX — sans cette
    // ligne, aucun de ses contrôles n'entre dans un sac, quelle que soit sa portée déclarée.
    //
    // CE QUE ÇA A COÛTÉ, mesuré le 2026-08-09 : `!(randomize)` refusait pendant que `!(shuffle)`,
    // `!(retro)` et `!(order)` passaient. Les trois qui marchent vivent sous `engine` ; `randomize`
    // vit sous `subgrammar`, traitée dix lignes plus haut dans sa propre table et JAMAIS versée ici.
    // Sa portée déclare pourtant `flow`. Il ne pouvait donc pas s'écrire dans le flux — et il le
    // pouvait la veille, uniquement parce qu'un DOUBLON `engine.randomize` existait. En supprimant
    // ce doublon (le même soir, à raison : deux déclarations du même contrôle avec des portées
    // divergentes), j'ai retiré la seule entrée qui le faisait participer.
    //
    // LA LEÇON, ET ELLE VAUT AU-DELÀ D'ICI : un doublon ne fait pas que dupliquer, il COMPENSE.
    // Celui-ci masquait ce trou depuis toujours ; le dédoublonnage n'a pas créé le défaut, il l'a
    // découvert. C'est pourquoi la réparation se fait ici et non en restaurant le doublon —
    // remettre la béquille rendrait le trou invisible pour la prochaine section.
    if (lib.subgrammar) {
      const dansLeFlux = Object.fromEntries(Object.entries(lib.subgrammar).filter(
        ([nom, def]) => nom !== '_comment' && def && Array.isArray(def.scope) && def.scope.includes('flow')));
      if (Object.keys(dansLeFlux).length) controlSources.push({ source: dansLeFlux, isEngine: true, section: 'subgrammar' });
    }
    // `groups` (ex-`runtime`, RENOMMÉ 2026-08-10 — le nom `runtime` est retiré partout, remplacé
    // par `resolvedBy` qui nomme l'outil DIRECTEMENT) : la SECTION de `lib/controls.json` qui
    // groupe ses sous-groupes de contrôles RUNTIME (musical/midi/audio/dispatcher/generic). Ne
    // collisionne plus avec le champ `runtime` d'un alphabet (sortie par défaut de la collection,
    // une chaîne — prototype de `LANGUAGE.md`), qui garde son nom : deux notions, deux noms.
    if (lib.groups && typeof lib.groups === 'object' && !Array.isArray(lib.groups)) {
      // Iterate sub-groups: each value that is an object with nested control defs
      for (const [groupName, groupContent] of Object.entries(lib.groups)) {
        if (groupName === '_comment') continue;
        if (typeof groupContent === 'object' && groupContent !== null && !Array.isArray(groupContent)) {
          // Check if this is a sub-group (has nested objects with 'args' or 'description')
          const hasNestedDefs = Object.values(groupContent).some(
            v => typeof v === 'object' && v !== null && ('args' in v || 'description' in v)
          );
          if (hasNestedDefs) {
            // Sub-group: iterate its controls, tag each with transportGroup
            for (const [name, def] of Object.entries(groupContent)) {
              if (name.startsWith('_')) continue;  // clé de DOCUMENTATION, cf. estUneDeclarationDeControle
              controlSources.push({ source: { [name]: { ...def, transportGroup: groupName } }, isEngine: false, section: `groups.${groupName}` });
            }
            continue;
          }
        }
        // Flat control (backwards compat): treat as ungrouped runtime control
        controlSources.push({ source: { [groupName]: groupContent }, isEngine: false, section: 'groups' });
      }
    }
    for (const { source, isEngine, section } of controlSources) {
      for (const [name, def] of Object.entries(source)) {
        // ⚠️ FRONTIÈRE DONNÉE → LANGAGE. Un fichier de données ne doit JAMAIS pouvoir agrandir le
        // langage en le commentant. On ne filtrait que la clé `_comment` : la première clé de
        // documentation d'une autre forme posée dans une section de contrôles est donc entrée AU
        // VOCABULAIRE comme un contrôle, en silence (mesuré le 2026-07-27 — 58 contrôles chargés,
        // le 58e était une ligne d'explication).
        //
        // LISTE BLANCHE, PAS LISTE NOIRE (architecte, 2026-07-27) : exclure des noms de clés
        // laisserait entrer la prochaine clé de commodité qui n'y figure pas. On exige donc la
        // FORME d'une déclaration, et tout ce qui ne l'a pas est REFUSÉ — bruyamment, sauf la
        // documentation, seule forme explicitement admise comme non-contrôle.
        if (name.startsWith('_')) continue;   // documentation : convention du dépôt, admise
        if (!estUneDeclarationDeControle(def)) {
          throw new Error(
            `lib '${dir.name}' : l'entrée '${name}' occupe une section de contrôles sans être une `
            + `déclaration de contrôle (il lui faut 'args' ET 'description'). Une clé de `
            + `documentation se préfixe par '_' ; sinon, c'est une entrée du VOCABULAIRE et elle `
            + `doit se déclarer comme telle — un fichier de données n'agrandit pas le langage en `
            + `le commentant.`);
        }
        declarer(name, `lib/${dir.name}.json → ${section}`);
        // ⛔ UN GESTE DÉCLARÉ POUR LE ROUTAGE N'EST PAS UN MOT DU LANGAGE ──────────────────────
        // RATIFIÉ PAR ROMAIN le 2026-08-13. Mes librairies ont DEUX MÉTIERS et ne savaient en dire
        // qu'un : elles portent le VOCABULAIRE BPScript — ce qu'un auteur écrit — ET l'AUTORITÉ DE
        // ROUTAGE que le frontal BP3 interroge pour traduire une grammaire native. Toute entrée
        // chargée entrait au vocabulaire, donc déclarer un geste le rendait forcément écrivable.
        //
        // CE QUE ÇA A COÛTÉ, le jour même : en retirant `value`, `fixed` et `cont` du langage —
        // leur graphie cassait deux canons, le paramètre est désormais la clé — j'ai retiré du même
        // geste la correspondance dont le frontal avait besoin. Le binaire les exécute toujours et
        // SIX grammaires du corpus les écrivent : il s'est retrouvé sans autorité sur des gestes
        // que le moteur fait.
        //
        // `bpscript: false` sépare les deux métiers. L'entrée remplit la graphie native et le
        // destinataire — le frontal route — mais son nom N'ENTRE PAS au vocabulaire : une scène qui
        // l'écrit est refusée comme avant. L'absence cesse d'être muette : un mot que je ne déclare
        // pas du tout est un TROU, un mot marqué ainsi est une DÉCISION.
        // Le frontal BP3 lit le BUNDLE, pas ce contexte : l'entrée reste dans la donnée, avec sa
        // graphie native — c'est tout ce dont il a besoin. Ici, on sort AVANT que le nom n'entre
        // dans `ctx.controls`, la table sur laquelle le vocabulaire du langage est construit.
        if (def.bpscript === false) continue;
        ctx.controls[name] = def;
        ctx.controlMap[name] = def.bp3 || `_${name}`;
        // Le destinataire se lit sur le FICHIER, jamais sur l'entrée chargée : une invocation à
        // sous-clé (`@tuning.just`) rend une entrée du catalogue, qui ne porte pas ce champ.
        // ── LE DESTINATAIRE SE SURCHARGE : le fichier donne le DÉFAUT, l'entrée TRANCHE ───────
        // RÈGLE DE ROMAIN (2026-08-13) : « si je définis le destinataire pour la librairie, c'est le
        // défaut de la librairie ; si je le définis sur le contrôle, c'est celui du contrôle qui
        // surcharge. » Même principe que partout ailleurs dans le langage — le plus LOCAL gagne.
        //
        // ⚠️ CE QUE ÇA RÉPARE, ET LE CAS EST D'AUJOURD'HUI. Sans surcharge, un fichier ne porte
        // qu'UN destinataire, donc un contrôle dont le résolveur diffère de ses frères doit CHANGER
        // DE FICHIER. C'est ce qui est arrivé ce matin à `articulcont` et `transposecont` : les
        // modes continus partent aux sorties, or ils vivaient chez `engine` (BPx) et `transpo`
        // (Kairos) — j'ai dû les déménager loin de leur paramètre pour respecter la règle. Avec la
        // surcharge, ils seraient restés auprès de leurs frères en nommant leur propre destinataire.
        // Le rangement cesse d'être dicté par une contrainte de fichier.
        const parDefaut = (loadJsonFile(dir.name) || {}).resolvedBy;
        const destinataire = (typeof def.resolvedBy === 'string' && def.resolvedBy)
          ? def.resolvedBy : parDefaut;
        if (destinataire) ctx.controlResolvedBy[name] = destinataire;
        // LA FORME PRÉFIXÉE EXISTE TOUJOURS, pas seulement en cas d'ambiguïté : `expression.vel`
        // s'écrit et se lit même quand `vel` seul suffit. Une graphie qui n'apparaîtrait qu'au
        // moment du conflit serait un mode de secours, donc une seconde grammaire.
        ctx.controlsQualified[`${dir.name}.${name}`] = def;
        if (destinataire) ctx.controlQualifiedResolvedBy[`${dir.name}.${name}`] = destinataire;
        // `implements:<librairie>.<contrôle>` — cette déclaration RÉALISE une interface générique.
        // On enregistre le lien dans les deux sens ; sa VALIDITÉ se vérifie une fois toutes les
        // librairies chargées, parce qu'une interface peut se déclarer après sa réalisation et
        // qu'un refus qui dépendrait de l'ordre de chargement serait l'arbitraire qu'on combat.
        if (typeof def.implements === 'string' && def.implements) {
          const qual = `${dir.name}.${name}`;
          ctx.implementedInterface[qual] = def.implements;
          (ctx.implementations[def.implements] = ctx.implementations[def.implements] || []).push(qual);
        }
        ctx.controlNames.add(name);
        // Engine section = BP3 native (temporal/structural: goto, tempo, repeat...)
        // Runtime section = dispatcher (sound/performance: vel, chan, wave...)
        if (isEngine) {
          ctx.bp3NativeControls.add(name);
          ctx.engineBagControls.add(name);   // SAC : ce contrôle s'écrit entre CROCHETS
          // scope:"seq_prefix" = serial tools emitted as prefix inside group/sequence
          if (def.scope === 'seq_prefix') {
            ctx.seqPrefixControls.add(name);
          }
        } else {
          ctx.dispatcherOnlyControls.add(name);
          ctx.runtimeBagControls.add(name);  // SAC : ce contrôle s'écrit entre PARENTHÈSES
        }
        if (!def.args || def.args.length === 0) {
          ctx.noArgControls.add(name);
        }
        // `bagOnly:true` — ce contrôle N'A PAS de forme nue dans le flux : il ne s'écrit que dans
        // son sac. Distinction que « sans argument » ne portait PAS, et cette confusion a coûté :
        // les contrôles continus hérités de BP3 (`volumecont`, `pitchcont`, `mapcont`…) s'écrivent
        // bel et bien nus au fil de la séquence — 10 scènes du corpus le font — tandis que
        // `mute`/`unmute`/`panic`, déclarés le 2026-07-26, n'ont jamais eu que la forme du sac.
        // Faute de le dire, tout mot sans argument devenait un mot du flux, et une scène qui
        // portait déjà ce nom était tronquée en silence (mesuré par Kairos, patchbay-demo).
        // Le marquage est POSITIF et porté par la donnée : le code ne nomme aucun contrôle.
        if (def.bagOnly === true) {
          ctx.bagOnlyControls.add(name);
        }
        // Contrôle désigné par un NUMÉRO DE COMPOSANT : `(cc.98:45)`. Le point APPELLE le
        // composant (le contrôleur 98), les deux points AFFECTENT la valeur — la règle d'or du
        // langage, appliquée par Romain le 2026-07-26 à un cas qui n'avait pas été traité.
        // DÉCLARATIF, jamais un nom en dur : le langage sait déjà nommer les contrôleurs qui ont
        // un alias (mod = CC1, volume = CC7) ; il lui manquait de pouvoir en désigner un
        // quelconque, et c'est ce trou que la forme positionnelle bouchait de travers.
        if (def.component === 'number') {
          ctx.componentControls.add(name);
        }
        // `scope:"rule"` — la procédure vaut pour la RÈGLE, pas pour un point de la séquence.
        // ⚠️ LE CHAMP EST DEVENU UNE LISTE le 2026-08-08 (Romain) : `scope: ['rule']` et non plus
        // `scope: 'rule'`. Cette comparaison stricte à une chaîne rendait donc FAUX pour tout le
        // monde, et la famille des procédures de niveau règle se vidait EN SILENCE — le garde qui
        // la surveille n'a rougi que parce qu'il ancre les quatre noms attendus.
        // On lit les deux formes le temps que plus rien n'écrive une chaîne : le garde ci-dessus
        // le dira, et la branche chaîne sort avec la dernière.
        // ⚠️ DEUX NOTIONS QUE `scope` NE DISTINGUE PAS, et les confondre change le ROUTAGE.
        // `ruleScopeControls` désigne les PROCÉDURES DU MOTEUR — `_goto`, `_failed`, `_repeat`,
        // `_stop` — que BPx extrait en métadonnée de règle. Ce n'est PAS « tout contrôle dont la
        // portée est la règle » : `scan`, `weight`, `on_fail` et `meter` ont la même portée et sont
        // des ATTRIBUTS STRUCTURELS, pas des procédures — la donnée le dit déjà, ils n'ont AUCUN
        // champ `bp3` (cf. `_reglages_reserves_doc`), justement parce qu'aucune procédure native ne
        // leur correspond. Mesuré le 2026-08-08 : en tirant la famille du seul `scope`, les quatre
        // y sont entrés et le refus de `![scan:…]` s'est mis à parler de procédure de règle.
        // Le critère joint donc les deux faits que la donnée porte déjà, et ne nomme aucun contrôle.
        // ⚠️ LE TROISIÈME FAIT, AJOUTÉ LE 2026-08-10 — et il remplace une longueur exacte qui
        // servait de proxy. Le critère exigeait `portees.length === 1`, ce qui écartait toute
        // procédure valant AUSSI ailleurs. `destru` en était : le moteur l'arme sur la règle
        // (Encode.c:408) comme sur la sous-grammaire (CompileGrammar.c:1528), donc sa portée est
        // `["subgrammar","rule"]` et la longueur le rejetait. `S -> C4 [destru]` tombait alors en
        // DRAPEAU — homonyme silencieux, puisque le crochet accepte tout mot comme drapeau.
        // Arbitrage Romain : « la portée règle, c'est un sac en fin de règle pour tous les
        // contrôles, ça doit être pareil pour destru, voilà comme pour stop ».
        //
        // CE QUE LA LONGUEUR PROTÉGEAIT VRAIMENT : que `staccato`, `legato` et `rndtime` n'entrent
        // pas — ce sont des contrôles de RENDU, pas des procédures de dérivation. Le fait qui les
        // sépare est déjà dans la donnée, et il est plus juste que la longueur : une PROCÉDURE
        // n'agit jamais sur un SYMBOLE ni sur un GROUPE, alors que les trois y valent. Le critère
        // ne nomme donc toujours aucun contrôle — il joint trois faits que la donnée porte.
        const portees = Array.isArray(def.scope) ? def.scope : (def.scope ? [def.scope] : []);
        if (portees.includes('rule') && typeof def.bp3 === 'string'
            && !portees.includes('symbol') && !portees.includes('group')) {
          ctx.ruleScopeControls.add(name);
        }
        // CE QUI A LE DROIT DE S'ÉCRIRE AU NIVEAU D'UNE RÈGLE — portée qui INCLUT `rule`, sans
        // exiger qu'elle soit seule. Distinct de `ruleScopeControls` : `rndtime` est ici (il vaut
        // aussi sur un symbole ou un groupe) et n'est pas une procédure.
        // ⚠️ SERT À NE PAS DOUBLER UN REFUS PLUS PRÉCIS. Le refus du crochet, côté parseur, ne
        // doit mordre que sur ce que l'aval LAISSE PASSER : un contrôle hors de sa portée est
        // déjà refusé par la confrontation des portées, avec un message qui donne sa vraie place
        // (« `@mode:…` en tête de sous-grammaire »). Mesuré le 2026-08-08 : sans cette
        // restriction, le refus générique du crochet interceptait `mode` en amont et FAISAIT
        // PERDRE sa réécriture — un message précis remplacé par un message vague est une
        // régression que seul un garde du message attrape.
        if (portees.includes('rule')) ctx.ruleAllowedControls.add(name);
        // Argument = intervalle musical (fraction/cents/décimal) : la surface lit une
        // valeur d'intervalle et la porte brute ; la résolution (Kairos) la normalise.
        if (def.argType === 'interval') {
          ctx.intervalControls.add(name);
        }
        // Argument COMPOSITE (ex. keyxpand `pivot,facteur`) : la virgule appartient à la
        // VALEUR, pas à la liste d'arguments. Sans ce marqueur la paire est scindée et le
        // contrôle ne reçoit que sa première moitié. Même principe que `interval` : porté
        // brut par la surface, découpé par l'aval qui en connaît la forme.
        if (def.argType === 'composite') {
          ctx.compositeControls.add(name);
        }
      }
    }

    // Compute dual-context controls: appear in both engine (bp3Native) and runtime (dispatcher)
    // These must always route to _script when used in () SettingBag context.
    for (const name of ctx.bp3NativeControls) {
      if (ctx.dispatcherOnlyControls.has(name)) {
        ctx.dualContextControls.add(name);
      }
    }

    // Merge symbols from lib.symbols
    if (lib.symbols) {
      for (const [name, def] of Object.entries(lib.symbols)) {
        ctx.symbols[name] = def;
      }
    }
    // Alphabet libs: defer terminal generation (needs octave convention resolved first)
    if (nomsDeTerminaux(lib)) {
      ctx._alphabets.push(lib);
      // Set default octave convention from alphabet (can be overridden by @octaves)
      if (lib.octaves) ctx._octaveConvention = lib.octaves;
    }
    // @octaves:xxx — override octave convention
    if (dir.name === 'octaves' && dir.runtime) {
      ctx._octaveConvention = dir.runtime;
    }
    // `@homomorphism.<table>` — charge une table de correspondances symbole → symbole.
    // ⚠️ LE MOT ÉTAIT `transcription` JUSQU'AU 2026-08-07 (« oui on renomme », Romain). La bible
    // n'a jamais écrit que `@homomorphism` — `transcription` n'y apparaît nulle part. Le code
    // implémentait donc l'ancien nom et REFUSAIT celui de la référence : 159 occurrences dans 13
    // scènes de l'écosystème écrivaient le mot mort, ZÉRO écrivait le bon.
    if (dir.name === 'homomorphism' && dir.subkey && (lib?.mappings || lib?.sections)) {
      ctx.transcriptions[dir.subkey] = lib;
    }

    // Merge CV objects (lib.type === "cv")
    if (lib.type === 'cv' && lib.objects) {
      const libName = lib.name || dir.name;
      for (const [objName, def] of Object.entries(lib.objects)) {
        ctx.cvObjects[`${libName}.${objName}`] = def;
      }
    }
  }

  // Generate terminals from deferred alphabets (after all directives processed)
  // Octave convention is now fully resolved (alphabet default + @octaves override)
  const octaveDef = ctx._octaveConvention
    ? loadLib('octaves')?.[ctx._octaveConvention]
    : null;

  for (const lib of ctx._alphabets) {
    if (octaveDef) {
      // Generate all combinations: note + alteration + register
      const alts = lib.alterations && typeof lib.alterations === 'object' && !Array.isArray(lib.alterations)
        ? Object.keys(lib.alterations)
        : (Array.isArray(lib.alterations) && lib.alterations.length > 0 ? lib.alterations : ['']);
      for (const note of nomsDeTerminaux(lib)) {
        for (const alt of alts) {
          for (const reg of octaveDef.registers) {
            const noteAlt = note + alt;
            const terminal = octaveDef.position === 'suffix'
              ? noteAlt + octaveDef.separator + reg
              : reg + octaveDef.separator + noteAlt;
            ctx.symbols[terminal] = { type: 'gate' };
            ctx.alphabetTerminals.push(terminal);
          }
        }
      }
    } else {
      // No octaves — terminals are just the raw notes (e.g. tabla, abc)
      for (const note of nomsDeTerminaux(lib)) {
        ctx.symbols[note] = { type: 'gate' };
        ctx.alphabetTerminals.push(note);
      }
    }
  }

  // ── UN `implements` POINTE UN MOT QUI EXISTE, ou la librairie est refusée ──────────────────────
  // FAIL-LOUD, à la déclaration : une réalisation qui vise une interface absente est un mot que
  // rien ne rend public. Sans ce refus, `midi.volume` réaliserait `expression.volme` et la faute
  // resterait muette — la réalisation cesserait simplement de lever l'ambiguïté, ce qui se lit
  // comme « deux homonymes » et pas comme « une coquille ».
  for (const [qual, cible] of Object.entries(ctx.implementedInterface)) {
    if (!ctx.controlsQualified[cible]) {
      throw new Error(
        `'${qual}' déclare 'implements:${cible}', et '${cible}' n'est déclaré nulle part. Une `
        + `réalisation vise une interface EXISTANTE, écrite '<librairie>.<contrôle>'.`);
    }
    if (cible === qual) {
      throw new Error(
        `'${qual}' déclare se réaliser lui-même. Une réalisation vise l'interface d'une AUTRE `
        + `librairie — celle que l'auteur écrit, quand la réalisation est celle du runtime actif.`);
    }
  }

  // ── LES NOMS AMBIGUS, une fois TOUTES les librairies chargées ────────────────────────────────
  // Le calcul ne peut pas se faire au fil de la boucle : une clé n'est ambiguë que par rapport à
  // ce qui sera chargé APRÈS elle, et le savoir à mi-parcours ferait dépendre le refus de l'ordre
  // de chargement — exactement l'arbitraire que ce mécanisme remplace.
  //
  // ⛔ UNE INTERFACE ET SES RÉALISATIONS NE SONT PAS DES HOMONYMES. Deux déclarations d'un même
  // nom SANS `implements` restent une erreur, inchangée. Avec `implements`, il n'y a qu'UNE entrée
  // publique — l'interface — et la forme nue y résout PAR CONSTRUCTION, jamais par une règle de
  // priorité : on n'arbitre pas entre deux candidats, il n'y en a qu'un.
  //
  // ⚠️ ET LA FORME NUE DOIT RÉSOUDRE VERS L'INTERFACE, PAS VERS LA DERNIÈRE LUE. `ctx.controls`
  // se remplit au fil du chargement, dernière écriture gagnante : sans cette reprise, `volume` nu
  // porterait la déclaration de `midi` — sa plage, son défaut et SON DESTINATAIRE — alors que
  // l'écriture générique doit partir au runtime actif quel qu'il soit. C'est exactement le choix
  // silencieux que la règle d'ambiguïté existe pour interdire.
  for (const [nom, origines] of provenance) {
    if (origines.size <= 1) continue;
    const quals = Object.keys(ctx.controlsQualified).filter((q) => q.slice(q.indexOf('.') + 1) === nom);
    const interfaces = quals.filter((q) => !ctx.implementedInterface[q]);
    const implementations = quals.filter((q) => ctx.implementedInterface[q]);
    const toutesVersLaMeme = implementations.length > 0 && interfaces.length === 1
      && implementations.every((q) => ctx.implementedInterface[q] === interfaces[0]);
    if (!toutesVersLaMeme) { ctx.ambiguousControls.add(nom); continue; }
    ctx.controls[nom] = ctx.controlsQualified[interfaces[0]];
    ctx.controlMap[nom] = ctx.controls[nom].bp3 || `_${nom}`;
    const dest = ctx.controlQualifiedResolvedBy[interfaces[0]];
    if (dest) ctx.controlResolvedBy[nom] = dest;
  }

  return ctx;
}

/**
 * VOCABULAIRE du langage — autorité UNIQUE, à destination de l'ÉDITEUR (Kanopi :
 * coloration syntaxique, autocomplétion, surlignage d'erreurs) ET du garde de
 * compilation (même agrégation, une seule source de vérité). Romain 2026-07-05.
 *
 * TOUT est agrégé depuis les libs chargées + le schéma @core — ZÉRO liste en dur,
 * ZÉRO lib nommée en dur. Une user library ajoutée = ses mots entrent ici
 * automatiquement (contrôles, valeurs, fonctions, entrées de catalogue).
 *
 * UNIVERS COMPLET : agrège TOUTES les librairies disponibles (registre = built-in +
 * user libs à venir), pas seulement celles que la scène invoque — un mot USABLE est
 * valide qu'on ait chargé sa lib ou non (principe Romain). `directives` est accepté
 * pour compat/future portée mais le vocabulaire renvoyé couvre tout le disponible.
 * @param {Array} [directives]  (optionnel) directives de la scène.
 * @returns {{
 *   keywords: string[],                       // mots du LANGAGE (réservés) — non des libs
 *   controls: Array<{name, args?, range?, values?, default?, description?, transportGroup?}>,
 *   values:   Array<{name, range?, unit?, values?, description?}>,
 *   functions: string[],                      // fonctions digitales (transpose…)
 *   components: { [axis:string]: string[] },  // entrées de catalogue par axe (alphabets, accordages…)
 *   addressKeys: string[],
 *   qualifierKeys: string[],                   // réglages réservés (mode/scan/weight/on_fail/tempx/meter), écrits en '()'
 *   modulationInputs: string[],
 *   directiveValues: { [directive:string]: {description?, values: [{name, description?}]} },  // enums (@mode:…, @scan:…)
 *   syntaxWords: { [word:string]: {kind, description?, syntax?} }                              // gate/trigger/cv/lambda, ->/<-/<>
 * }}
 */
function describeVocabulary(directives = []) {
  // DEUX QUESTIONS, DEUX PORTÉES — et la signature les distinguait déjà sans que le corps le fasse.
  //
  // · SANS directives : « quel est le vocabulaire du langage ? » — le CATALOGUE complet, toutes les
  //   librairies du registre. C'est ce que Kanopi affiche à l'auteur, et c'est légitime.
  // · AVEC directives : « qu'est-ce que CETTE scène a le droit d'écrire ? » — les seules librairies
  //   qu'elle invoque.
  //
  // ⚠️ LE PARAMÈTRE EXISTAIT ET ÉTAIT IGNORÉ : le corps reconstruisait l'univers complet dans tous
  // les cas. Une signature qui accepte un argument sans l'employer est pire qu'une absence — elle
  // fait croire que la restriction est possible, et personne ne va vérifier. Le contrôle des
  // références passait donc par ici sans rien restreindre, et son propre commentaire portait la
  // règle inverse : « agrégat de TOUTES les libs disponibles. Un mot usable est valide. »
  //
  // Romain a tranché l'autre sens le 2026-08-08 : « invoquer commande, systématiquement — si un mot
  // est inconnu dans le corpus invoqué, alors erreur ».
  const aUneScene = Array.isArray(directives) && directives.length > 0;
  const allDirs = aUneScene ? directives : Object.keys(registry).map((name) => ({ name }));
  const ctx = loadLibsFromDirectives(allDirs);
  const isEntry = (v) => v && typeof v === 'object' && !Array.isArray(v);
  const META = new Set(['name', 'description', 'version', 'resolvedBy']);
  const components = {};
  for (const axis of ctx.catalogAxes) {
    const file = loadLib(axis);
    // DEUX FORMES DE FICHIER, ET LE CHOIX EST MESURÉ. Les librairies de DONNÉES posent leurs
    // entrées à la RACINE (`alphabets.json` → western, sargam…) ; celles de CODE les groupent
    // sous `objects` (`mod.json`, `voices.json`, et `eval.json` depuis le 2026-08-06). Aucun
    // fichier ne fait les deux — vérifié sur les huit concernés avant d'écrire cette ligne, ce
    // qui est la raison pour laquelle `objects` peut primer sans rien ambiguïser.
    // Sans ce cas, un axe de catalogue dont les entrées vivent sous `objects` rendait une liste
    // VIDE : tout nom y devenait inconnu, ou — pire, et c'est ce qui est arrivé — la déclaration
    // de l'axe restait sans effet et n'importe quel nom passait en silence.
    components[axis] = file
      ? (file.objects && isEntry(file.objects)
          ? Object.keys(file.objects).filter((k) => !k.startsWith('_'))
          : Object.keys(file).filter((k) => !k.startsWith('_') && !META.has(k) && isEntry(file[k])))
      : [];
  }
  const pick = (def, keys) => {
    const o = {};
    for (const k of keys) if (def[k] !== undefined) o[k] = def[k];
    return o;
  };
  // Schéma SYNTAXE (mots/opérateurs + enums de directive) — lib `language.json`, autorité machine.
  const langLib = loadJsonFile('language') || {};
  // Voix (LANG-SONS-2, lib/voices.json §3) : noms de BASE pour `voice.<nom>` — les clés
  // `nom for:<device>` (spécialisations §5) se replient sur leur nom de base.
  const voicesLib = loadJsonFile('voices');
  const voiceNames = [...new Set(Object.keys((voicesLib && voicesLib.objects) || {})
    .map((k) => k.replace(/\s+for:\S+$/, '')))];
  return {
    voices: voiceNames,
    keywords: [...ctx.reservedDirectiveNames],
    controls: Object.entries(ctx.controls).map(([name, def]) =>
      ({ name, ...pick(def || {}, ['args', 'range', 'values', 'default', 'description', 'transportGroup']) })),
    values: Object.entries(ctx.valueRegistry).map(([name, spec]) =>
      ({ name, ...pick(spec || {}, ['range', 'unit', 'values', 'description']) })),
    functions: [...ctx.digitalFunctions],
    components,
    addressKeys: [...ctx.addressKeys],
    // Réglages RÉSERVÉS (mode/scan/weight/on_fail/tempx/meter) — écrits en PARENTHÈSES depuis la
    // décision Romain 2026-08-02 (LANGUAGE.md:773-800). Exposé pour que le vocabulaire consommé
    // par validateReferences() les reconnaisse comme des attributs `(k:v)` connus.
    qualifierKeys: [...ctx.qualifierKeys],
    modulationInputs: [...ctx.modulationInputsAll],
    directiveValues: langLib.directiveValues || {},
    syntaxWords: langLib.syntaxWords || {},
  };
}

export { loadLib, directiveDeclareeParLaLibrairie, porteesDeclarees, groupeDUnicite, fichierDeLAxe, resolveActorAlphabet, resolveActorAlphabetSource, loadLibsFromDirectives, describeVocabulary, universeControlNames, universeIntervalControls, universeCompositeControls, universeComponentControls, universeRuleScopeControls, universeRuleAllowedControls, universeSacs, universeAddressKeys, registerLib, registerAll, clearRegistry,
  nomsDeTerminaux,
};
