// AUTORITÉ résolution acteur / pitch / contrôles : LIRE src/transpiler/_AUTORITE.md avant de modifier.
/**
 * BPScript Library Loader
 *
 * Loads lib/*.json files based on @ directives in the source.
 * Convention: @file → lib/file.json
 *             @file.key → lib/file.json → entry "key"
 *             @file.key:runtime → load + bind to runtime
 *
 * Browser-compatible BY CONSTRUCTION: this module does NO filesystem access and
 * NO top-level await. Every lib is pre-bundled as plain JS objects in libs-data.js
 * (generated by libs-bundle.js from lib/*.json) and auto-registered below — so the
 * exact same import chain loads in Node AND under a browser bundler (Vite/esbuild).
 * No `node:`/`fs` anywhere in the public import graph. Host code can still add or
 * override libs with registerLib()/registerAll().
 *
 * ⚠ After editing any lib/*.json, regenerate the bundle:
 *     node src/transpiler/libs-bundle.js > src/transpiler/libs-data.js
 */

import { LIBS as BUNDLED_LIBS } from './libs-data.js';

// Registry: pre-loaded libs (browser or Node pre-registration)
const registry = {};

// Cache loaded libs (from filesystem or registry)
const cache = {};

/**
 * Register a single lib by name (e.g. "controls" → contents of lib/controls.json).
 */
function registerLib(name, data) {
  registry[name] = data;
  cache[name] = data;  // also populate cache
  _universeControls = null;  // le registre a bougé → recalculer l'univers
}

/**
 * Register multiple libs at once.
 * @param {Object} libs - { name: data, ... }
 */
function registerAll(libs) {
  for (const [name, data] of Object.entries(libs)) {
    registerLib(name, data);
  }
}

/**
 * Clear all registered libs and cache (for testing).
 */
function clearRegistry() {
  for (const k of Object.keys(registry)) delete registry[k];
  for (const k of Object.keys(cache)) delete cache[k];
  _universeControls = null;
}

/**
 * Noms de contrôles de l'UNIVERS — toutes les libs du registre (built-in + user), et non les
 * seules libs que la scène a chargées via ses directives. Sert au garde des clés `[]` : un
 * `[rotate:2]` est une clé CONNUE du langage même dans une scène qui ne déclare pas `@controls`.
 * (Savoir si `@controls` doit être exigé pour l'employer est une question de surface, non tranchée.)
 */
let _universeControls = null;
function universeControlNames() {
  if (!_universeControls) {
    const allDirs = Object.keys(registry).map((name) => ({ name }));
    _universeControls = loadLibsFromDirectives(allDirs).controlNames;
  }
  return _universeControls;
}

// Contrôles interval-typés de l'UNIVERS (marqués `argType:"interval"` dans une lib). Sert au parseur
// AVANT que le libCtx de la scène soit chargé : une directive globale `@transpose:-2400c` doit lire
// une valeur d'INTERVALLE (chaîne brute) dès l'analyse des directives, avant tout consommateur.
let _universeIntervalControls = null;
function universeIntervalControls() {
  if (!_universeIntervalControls) {
    const allDirs = Object.keys(registry).map((name) => ({ name }));
    _universeIntervalControls = loadLibsFromDirectives(allDirs).intervalControls;
  }
  return _universeIntervalControls;
}

// Auto-register the pre-bundled libs at module load (Node AND browser).
// This replaces the former Node-only `fs` fallback: the registry is always
// populated from libs-data.js, so loadJsonFile never needs the filesystem.
registerAll(BUNDLED_LIBS);

// Canonical filenames (directive name → JSON file name)
// `tuning` → tunings.json = le CATALOGUE servi (PITCH_LIB). Avant cet alias,
// loadLib('tuning', X) tombait sur lib/tuning.json (héritage Bernard, gammes sous
// .scales) et ne résolvait JAMAIS rien — la résolution d'accordage était 100 %
// aval (Kairos). L'alias ouvre l'accès transpileur au catalogue (SCENE_VALUES).
// `scale` → scales.json : axe-composant à catalogue (domain:scale) promu au CUTOVER universel
// (Romain 2026-07-14, tour [412]) — ouvre l'accès transpileur pour valider `@scale.<nom>`.
const fileAliases = { alphabet: 'alphabets', tuning: 'tunings', scale: 'scales' };

function loadJsonFile(name) {
  const canonical = fileAliases[name] || name;
  if (cache[canonical]) return cache[canonical];

  // Try registry first (canonical then original name)
  const regData = registry[canonical] || registry[name];
  if (regData) {
    cache[canonical] = regData;
    return regData;
  }

  return null;
}

/**
 * Load a lib by name, with optional subkey.
 * @file → lib/file.json (whole file)
 * @file.subkey → lib/file.json → entry from the top-level collection
 *
 * For alphabets.json: the collection key is "alphabets"
 * For sub.json: the collection key is "tables"
 * Generic fallback: tries the subkey directly on the root object
 */
function loadLib(name, subkey) {
  if (subkey) {
    const file = loadJsonFile(name);
    if (file) {
      // Look for subkey in known collection fields, or directly on root
      const entry = file.alphabets?.[subkey] || file.tables?.[subkey] || file[subkey];
      if (entry) return entry;
    }
    // Fallback: try name/subkey as a separate file (e.g. settings/visser2.json)
    const subFile = loadJsonFile(name + '/' + subkey);
    if (subFile) return subFile;
    return null;
  }

  // No subkey — load the whole file
  return loadJsonFile(name);
}

/**
 * Load all libraries referenced by @ directives in the AST.
 * Returns a merged context: { controls, controlMap, noArgControls, symbols }
 */
function loadLibsFromDirectives(directives) {
  const ctx = {
    controls: {},       // name → { bp3, args, ... }
    controlMap: {},     // name → bp3 name (e.g. "vel" → "_vel")
    controlNames: new Set(),
    bp3NativeControls: new Set(),  // controls BP3 understands natively (no "transport" field)
    seqPrefixControls: new Set(),  // engine controls with scope:"seq_prefix" — emitted as prefix inside group/sequence
    dispatcherOnlyControls: new Set(),  // controls only the dispatcher understands (have "transport" field, e.g. audio)
    dualContextControls: new Set(),  // controls that appear in BOTH engine and runtime — in () always route to _script
    subgrammarControls: new Map(),  // subgrammar-level directives: name → { bp3, args }
    noArgControls: new Set(),
    intervalControls: new Set(),  // controls whose argument is a MUSICAL INTERVAL (fraction 3/2, cents 700c,
                                  // decimal 1.5) — marqués `argType:"interval"` dans la lib. La valeur est
                                  // portée BRUTE (chaîne) et résolue en aval par normalizeRatio (Kairos).
    symbols: {},        // name → { type, ... }
    alphabetTerminals: [],  // terminaux issus des SEULS alphabets (sans @core etc.) —
                            // porte du découpeur mono-char (bpxAst.js, flip Palier 4 étape A)
    cvObjects: {},      // "lib.type" → def (e.g. "mod.adsr" → { parameters, ... })
    _libs: {},          // directive name → raw lib data (for generator access)
    _alphabets: [],     // loaded alphabet libs (deferred terminal generation)
    _octaveConvention: null,  // resolved octave convention name
    transcriptions: {},  // name → { mappings: { a: b, ... } }
    // SCENE_VALUES (hub [293]) : registre GÉNÉRIQUE des valeurs déclarées par les
    // librairies chargées (section top-level `values` d'un fichier lib). Une valeur
    // ajoutée demain à une lib = une entrée JSON, zéro code. nom → spec
    // { unit?, range?, values?, default?, componentDefault?, description?, _axis }.
    // `_axis` = clé d'entité d'acteur du fichier déclarant (tuning, alphabet…) —
    // sert à résoudre `componentDefault` sur le composant référencé par l'acteur.
    valueRegistry: {},
    valueRegistryErrors: [],  // collisions de noms (réservés/contrôles) — remontées à l'émission
  };

  // SOCLE @core + SCHÉMA du langage — chargés en DONNÉE, plus aucune liste en dur (Romain
  // 2026-07-05, prépare user libraries + partage du vocabulaire à Kanopi). @core.schema
  // déclare : `reservedDirectives` (mots de directive du langage, non-valeurs), `addressKeys`
  // (clés d'adresse de sortie), `catalogAxes` (axes dont les valeurs sont des entrées de
  // catalogue). @core.defaults porte les valeurs/composants par défaut (cascade).
  const coreLib = loadJsonFile('core') || {};
  const schema = coreLib.schema || {};
  ctx.reservedDirectiveNames = new Set(schema.reservedDirectives || []);
  ctx.addressKeys = new Set(schema.addressKeys || []);
  // Clés réservées de `[]` (docs/spec/LANGUAGE.md §« Clés reservees de [] ») : elles ne sont
  // pas des contrôles de librairie, le compilateur les comprend lui-même. Toute autre clé
  // dans `[]` est une erreur de compilation (ibid.) — cf. checkQualifierKey() du parser.
  ctx.qualifierKeys = new Set(schema.qualifierKeys || []);
  ctx.catalogAxes = Array.isArray(schema.catalogAxes) ? schema.catalogAxes.slice() : [];
  ctx.defaultComponents = (coreLib.defaults && coreLib.defaults.components) || {};

  const mergeValueRegistry = (file, axis) => {
    if (!file || !file.values || typeof file.values !== 'object') return;
    for (const [vname, spec] of Object.entries(file.values)) {
      if (vname.startsWith('_') || !spec || typeof spec !== 'object') continue;
      if (ctx.reservedDirectiveNames.has(vname) || ctx.controlNames.has(vname)) {
        ctx.valueRegistryErrors.push({
          message: `Valeur de librairie '${vname}' : nom réservé (directive moteur ou contrôle existant) — renommer dans la librairie`,
        });
        continue;
      }
      ctx.valueRegistry[vname] = { ...spec, _axis: axis || null };
    }
  };

  // @core.defaults.values : valeurs socle (diapason…) au registre (le nom `diapason` est
  // dans reservedDirectives pour bloquer une collision de lib, mais le socle @core le pose ici).
  if (coreLib.defaults && coreLib.defaults.values) {
    for (const [vname, spec] of Object.entries(coreLib.defaults.values)) {
      if (vname.startsWith('_') || !spec || typeof spec !== 'object') continue;
      ctx.valueRegistry[vname] = { ...spec, _axis: null };
    }
  }

  // Fonctions DIGITALES/dispatcher (transpose, rotate, keyxpand…) — toujours disponibles,
  // indépendantes de @controls. Source : digital.json (générique — une fonction ajoutée = reconnue).
  const digitalLib = loadJsonFile('digital');
  ctx.digitalFunctions = new Set(Object.keys((digitalLib && digitalLib.objects) || {}));

  // Always load settings (engine defaults)
  const settingsLib = loadLib('settings');
  if (settingsLib) ctx._libs['settings'] = settingsLib;

  // Registre des ENTRÉES DE MODULATION par type de sortie (lib/modulation.json) — toujours
  // disponible (intrinsèque, pas besoin de @modulation). Utilisé pour valider les noms écrits
  // au point de branchement `(cutoff: env1)`. modulationInputs : { type → Set(noms) } ;
  // modulationInputsAll : union de tous les noms (fallback quand le type de sortie n'est pas résolu).
  ctx.modulationInputs = {};
  ctx.modulationInputsAll = new Set();
  const modulationLib = loadLib('modulation');
  if (modulationLib) {
    for (const [type, inputs] of Object.entries(modulationLib)) {
      if (type.startsWith('_') || !inputs || typeof inputs !== 'object') continue;
      const set = new Set(Object.keys(inputs));
      ctx.modulationInputs[type] = set;
      for (const n of set) ctx.modulationInputsAll.add(n);
    }
    ctx._libs['modulation'] = modulationLib;
  }

  // Built-in: cc() generic MIDI CC (always available)
  ctx.controls['cc'] = { args: ['number', 'value'], range: [0, 127], description: 'Generic MIDI CC', transportGroup: 'midi' };
  ctx.controlMap['cc'] = '_cc';
  ctx.controlNames.add('cc');
  ctx.dispatcherOnlyControls.add('cc');

  // v0.8 — `sound` est une clé runtime_qualifier acceptée pour les overrides
  // inline (niveau 7 de la cascade : `Sa(sound.bell_short)`). Sémantique : le
  // dispatcher résout la référence pointée au playback. Décision PM 4.
  ctx.controls['sound'] = { args: ['value'], description: 'Inline sound override (v0.8)', transportGroup: 'dispatcher' };
  ctx.controlMap['sound'] = '_sound';
  ctx.controlNames.add('sound');
  ctx.dispatcherOnlyControls.add('sound');

  // Built-in subgrammar-level performance controls (always available, #146).
  // BP3 engine treats _mm/_striated/_smooth as "performance controls" emitted
  // on top of the first subgrammar — cf. CompileGrammar.c cases 13 (_mm),
  // 14 (_striated), 15 (_smooth), and CompileProcs.c GetPerformanceControl.
  // _destru is the destructuring directive. These are core engine instructions,
  // not optional library controls, so they must be encodable even when no lib
  // (e.g. @controls) is referenced. Without this seed, @mm/@striated/@smooth
  // were silently dropped from the produced BP3 grammar unless @controls was
  // loaded, breaking oracle reproducibility via compileBPS→wasm (#146 / Front #139).
  // A loaded lib's `subgrammar` section may still override these defaults below.
  ctx.subgrammarControls.set('mm', { bp3: '_mm', args: ['bpm'] });
  ctx.subgrammarControls.set('striated', { bp3: '_striated', args: [] });
  ctx.subgrammarControls.set('smooth', { bp3: '_smooth', args: [] });
  ctx.subgrammarControls.set('destru', { bp3: '_destru', args: [] });

  for (const dir of directives) {
    // @cc directives: user-defined named CC mappings
    if (dir.name === 'cc' && dir.ccMappings) {
      for (const cc of dir.ccMappings) {
        ctx.controls[cc.name] = {
          args: ['value'], range: [0, 127], default: 0,
          description: `User CC${cc.number}`, transportGroup: 'midi', ccNumber: cc.number
        };
        ctx.controlMap[cc.name] = `_${cc.name}`;
        ctx.controlNames.add(cc.name);
        ctx.dispatcherOnlyControls.add(cc.name);
      }
      continue;
    }

    // SCENE_VALUES : les références d'entité d'un @actor (alphabet/tuning/octaves)
    // touchent leurs fichiers-catalogues → leurs sections `values` entrent au registre
    // (sinon une scène 100 % acteurs n'aurait aucun registre). Le fichier est chargé,
    // pas l'entrée — la résolution du composant reste à l'émission/en aval.
    // (Les acteurs sont hissés par le parseur dans ast.actors — type ActorDirective,
    //  name = nom de l'acteur ; l'émission BPx les inclut dans la liste passée ici.)
    if ((dir.type === 'ActorDirective' || dir.name === 'actor') && dir.properties) {
      for (const axis of ['alphabet', 'tuning', 'octaves']) {
        if (dir.properties[axis]) mergeValueRegistry(loadJsonFile(axis), axis);
      }
      continue;
    }

    const lib = loadLib(dir.name, dir.subkey);
    // Section `values` du FICHIER de la directive (ex. @tuning.X → tunings.json),
    // même si l'entrée subkey n'existe pas (le registre est au niveau fichier).
    mergeValueRegistry(loadJsonFile(dir.name), dir.name);
    if (!lib) continue;
    const libKey = dir.subkey ? `${dir.name}.${dir.subkey}` : dir.name;
    ctx._libs[libKey] = lib;

    // Merge subgrammar-level directives (destru, striated, smooth, mm)
    if (lib.subgrammar) {
      for (const [name, def] of Object.entries(lib.subgrammar)) {
        if (name === '_comment') continue;
        ctx.subgrammarControls.set(name, def);
      }
    }

    // Merge controls — engine (BP3 native) and runtime (dispatcher)
    // Runtime section may contain sub-groups (musical, midi, audio, dispatcher, generic)
    const controlSources = [];
    if (lib.controls) controlSources.push({ source: lib.controls, isEngine: false });
    if (lib.engine) controlSources.push({ source: lib.engine, isEngine: true });
    if (lib.runtime) {
      // Iterate sub-groups: each value that is an object with nested control defs
      for (const [groupName, groupContent] of Object.entries(lib.runtime)) {
        if (groupName === '_comment') continue;
        if (typeof groupContent === 'object' && groupContent !== null && !Array.isArray(groupContent)) {
          // Check if this is a sub-group (has nested objects with 'args' or 'description')
          const hasNestedDefs = Object.values(groupContent).some(
            v => typeof v === 'object' && v !== null && ('args' in v || 'description' in v)
          );
          if (hasNestedDefs) {
            // Sub-group: iterate its controls, tag each with transportGroup
            for (const [name, def] of Object.entries(groupContent)) {
              if (name === '_comment') continue;
              controlSources.push({ source: { [name]: { ...def, transportGroup: groupName } }, isEngine: false });
            }
            continue;
          }
        }
        // Flat control (backwards compat): treat as ungrouped runtime control
        controlSources.push({ source: { [groupName]: groupContent }, isEngine: false });
      }
    }
    for (const { source, isEngine } of controlSources) {
      for (const [name, def] of Object.entries(source)) {
        if (name === '_comment') continue;
        ctx.controls[name] = def;
        ctx.controlMap[name] = def.bp3 || `_${name}`;
        ctx.controlNames.add(name);
        // Engine section = BP3 native (temporal/structural: goto, tempo, repeat...)
        // Runtime section = dispatcher (sound/performance: vel, chan, wave...)
        if (isEngine) {
          ctx.bp3NativeControls.add(name);
          // scope:"seq_prefix" = serial tools emitted as prefix inside group/sequence
          if (def.scope === 'seq_prefix') {
            ctx.seqPrefixControls.add(name);
          }
        } else {
          ctx.dispatcherOnlyControls.add(name);
        }
        if (!def.args || def.args.length === 0) {
          ctx.noArgControls.add(name);
        }
        // Argument = intervalle musical (fraction/cents/décimal) : la surface lit une
        // valeur d'intervalle et la porte brute ; la résolution (Kairos) la normalise.
        if (def.argType === 'interval') {
          ctx.intervalControls.add(name);
        }
      }
    }

    // Compute dual-context controls: appear in both engine (bp3Native) and runtime (dispatcher)
    // These must always route to _script when used in () RuntimeQualifier context.
    for (const name of ctx.bp3NativeControls) {
      if (ctx.dispatcherOnlyControls.has(name)) {
        ctx.dualContextControls.add(name);
      }
    }

    // Merge symbols from lib.symbols
    if (lib.symbols) {
      for (const [name, def] of Object.entries(lib.symbols)) {
        ctx.symbols[name] = def;
      }
    }
    // Alphabet libs: defer terminal generation (needs octave convention resolved first)
    if (lib.notes && Array.isArray(lib.notes)) {
      ctx._alphabets.push(lib);
      // Set default octave convention from alphabet (can be overridden by @octaves)
      if (lib.octaves) ctx._octaveConvention = lib.octaves;
    }
    // @octaves:xxx — override octave convention
    if (dir.name === 'octaves' && dir.runtime) {
      ctx._octaveConvention = dir.runtime;
    }
    // @transcription.xxx — load transcription table (homomorphism)
    if (dir.name === 'transcription' && dir.subkey && (lib?.mappings || lib?.sections)) {
      ctx.transcriptions[dir.subkey] = lib;
    }

    // Merge CV objects (lib.type === "cv")
    if (lib.type === 'cv' && lib.objects) {
      const libName = lib.name || dir.name;
      for (const [objName, def] of Object.entries(lib.objects)) {
        ctx.cvObjects[`${libName}.${objName}`] = def;
      }
    }
  }

  // Generate terminals from deferred alphabets (after all directives processed)
  // Octave convention is now fully resolved (alphabet default + @octaves override)
  const octaveDef = ctx._octaveConvention
    ? loadLib('octaves')?.[ctx._octaveConvention]
    : null;

  for (const lib of ctx._alphabets) {
    if (octaveDef) {
      // Generate all combinations: note + alteration + register
      const alts = lib.alterations && typeof lib.alterations === 'object' && !Array.isArray(lib.alterations)
        ? Object.keys(lib.alterations)
        : (Array.isArray(lib.alterations) && lib.alterations.length > 0 ? lib.alterations : ['']);
      for (const note of lib.notes) {
        for (const alt of alts) {
          for (const reg of octaveDef.registers) {
            const noteAlt = note + alt;
            const terminal = octaveDef.position === 'suffix'
              ? noteAlt + octaveDef.separator + reg
              : reg + octaveDef.separator + noteAlt;
            ctx.symbols[terminal] = { type: 'gate' };
            ctx.alphabetTerminals.push(terminal);
          }
        }
      }
    } else {
      // No octaves — terminals are just the raw notes (e.g. tabla, abc)
      for (const note of lib.notes) {
        ctx.symbols[note] = { type: 'gate' };
        ctx.alphabetTerminals.push(note);
      }
    }
  }

  return ctx;
}

/**
 * VOCABULAIRE du langage — autorité UNIQUE, à destination de l'ÉDITEUR (Kanopi :
 * coloration syntaxique, autocomplétion, surlignage d'erreurs) ET du garde de
 * compilation (même agrégation, une seule source de vérité). Romain 2026-07-05.
 *
 * TOUT est agrégé depuis les libs chargées + le schéma @core — ZÉRO liste en dur,
 * ZÉRO lib nommée en dur. Une user library ajoutée = ses mots entrent ici
 * automatiquement (contrôles, valeurs, fonctions, entrées de catalogue).
 *
 * UNIVERS COMPLET : agrège TOUTES les librairies disponibles (registre = built-in +
 * user libs à venir), pas seulement celles que la scène invoque — un mot USABLE est
 * valide qu'on ait chargé sa lib ou non (principe Romain). `directives` est accepté
 * pour compat/future portée mais le vocabulaire renvoyé couvre tout le disponible.
 * @param {Array} [directives]  (optionnel) directives de la scène.
 * @returns {{
 *   keywords: string[],                       // mots du LANGAGE (réservés) — non des libs
 *   controls: Array<{name, args?, range?, values?, default?, description?, transportGroup?}>,
 *   values:   Array<{name, range?, unit?, values?, description?}>,
 *   functions: string[],                      // fonctions digitales (transpose…)
 *   components: { [axis:string]: string[] },  // entrées de catalogue par axe (alphabets, accordages…)
 *   addressKeys: string[],
 *   modulationInputs: string[],
 *   directiveValues: { [directive:string]: {description?, values: [{name, description?}]} },  // enums (@mode:…, @scan:…)
 *   syntaxWords: { [word:string]: {kind, description?, syntax?} }                              // gate/trigger/cv/lambda, ->/<-/<>
 * }}
 */
function describeVocabulary(directives = []) {
  // Univers COMPLET : toutes les libs du registre (built-in + user), pas seulement la scène.
  const allDirs = Object.keys(registry).map((name) => ({ name }));
  const ctx = loadLibsFromDirectives(allDirs);
  const isEntry = (v) => v && typeof v === 'object' && !Array.isArray(v);
  const META = new Set(['name', 'description', 'version', 'domain']);
  const components = {};
  for (const axis of ctx.catalogAxes) {
    const file = loadLib(axis);
    components[axis] = file
      ? Object.keys(file).filter((k) => !k.startsWith('_') && !META.has(k) && isEntry(file[k]))
      : [];
  }
  const pick = (def, keys) => {
    const o = {};
    for (const k of keys) if (def[k] !== undefined) o[k] = def[k];
    return o;
  };
  // Schéma SYNTAXE (mots/opérateurs + enums de directive) — lib `language.json`, autorité machine.
  const langLib = loadJsonFile('language') || {};
  // Voix (LANG-SONS-2, lib/voices.json §3) : noms de BASE pour `voice.<nom>` — les clés
  // `nom for:<device>` (spécialisations §5) se replient sur leur nom de base.
  const voicesLib = loadJsonFile('voices');
  const voiceNames = [...new Set(Object.keys((voicesLib && voicesLib.objects) || {})
    .map((k) => k.replace(/\s+for:\S+$/, '')))];
  return {
    voices: voiceNames,
    keywords: [...ctx.reservedDirectiveNames],
    controls: Object.entries(ctx.controls).map(([name, def]) =>
      ({ name, ...pick(def || {}, ['args', 'range', 'values', 'default', 'description', 'transportGroup']) })),
    values: Object.entries(ctx.valueRegistry).map(([name, spec]) =>
      ({ name, ...pick(spec || {}, ['range', 'unit', 'values', 'description']) })),
    functions: [...ctx.digitalFunctions],
    components,
    addressKeys: [...ctx.addressKeys],
    modulationInputs: [...ctx.modulationInputsAll],
    directiveValues: langLib.directiveValues || {},
    syntaxWords: langLib.syntaxWords || {},
  };
}

export { loadLib, loadLibsFromDirectives, describeVocabulary, universeControlNames, universeIntervalControls, registerLib, registerAll, clearRegistry };
