/**
 * BPscript Prototype Generator
 *
 * Generates BP3 -so. (Sound Object) prototype files.
 * Each terminal gets a minimal prototype with a NoteOn/NoteOff pair
 * that gives it a reference duration. BP3 dilates based on context.
 *
 * MIDI encoding: value = time * 256 + byte (Euclidean division)
 */

/**
 * Generate ALL possible western note terminals (bolC0-bolB9 + accidentals).
 * Called once at startup to pre-populate BP3's prototype table.
 */
export function allWesternTerminals() {
  const notes = ['C', 'C#', 'Db', 'D', 'D#', 'Eb', 'E', 'F', 'F#', 'Gb', 'G', 'G#', 'Ab', 'A', 'A#', 'Bb', 'B'];
  const octaves = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
  const terminals = [];
  for (const note of notes) {
    for (const oct of octaves) {
      terminals.push(`bol${note}${oct}`);
    }
  }
  return terminals;
}

/**
 * Generate a -so. prototype file for a list of terminal names.
 * @param {string[]} terminals - terminal names (e.g. ['bolC4', 'bolD4', 'env1'])
 * @param {number} [duration=1000] - reference duration in ms
 * @returns {string} - -so. file content
 */
export function generatePrototypes(terminals, duration = 1000) {
  if (!terminals || terminals.length === 0) return '';

  const lines = [];

  // Header
  lines.push('// Bol Processor BP3');
  lines.push('// Object prototypes generated by BPscript');
  lines.push('84');    // tick key
  lines.push('1');     // tick channel
  lines.push('64');    // tick velocity
  lines.push('');      // empty line
  lines.push(String(terminals.length));  // number of prototypes

  // Object entries
  for (let i = 0; i < terminals.length; i++) {
    lines.push(`<HTML>${terminals[i]}</HTML>`);
    lines.push(...prototypeProperties());
    lines.push(...csoundSection());
    lines.push(...midiSection(duration));
    // Comment after MIDI bytes (required between prototypes, not after last)
    if (i < terminals.length - 1) {
      lines.push('<HTML></HTML>');
    }
  }

  // Footer
  lines.push('DATA:');
  lines.push('<HTML></HTML>');
  lines.push('_endSoundObjectFile_');

  return lines.join('\n');
}

/**
 * 49 mandatory properties for a minimal prototype.
 */
function prototypeProperties() {
  return [
    '1',              // 1. Object type: 1 = MIDI
    '1',              // 2. Resolution
    '0',              // 3. Default channel
    '1000',           // 4. Tref (reference time)
    '0',              // 5. Quantization
    '10000010110000111100', // 6. Pivot/mode flags (binary string)
    '0',              // 7. Rescale mode
    '0.0000',         // 8. Alpha min
    '0.0000',         // 9. Alpha max
    '-1',             // 10. Delay mode
    '0',              // 11. Max delay
    '-1',             // 12. Forward mode
    '0',              // 13. Max forward
    '1',              // 14. Break tempo mode
    '1000',           // 15. Max break tempo
    '1',              // 16. Cont beg mode
    '0',              // 17. Max beg gap
    '1',              // 18. Cont end mode
    '0',              // 19. Max end gap
    '0',              // 20. Cover beg mode
    '100',            // 21. Max cover beg
    '0',              // 22. Cover end mode
    '100',            // 23. Max cover end
    '1',              // 24. Trunc beg mode
    '0',              // 25. Max trunc beg
    '1',              // 26. Trunc end mode
    '0',              // 27. Max trunc end
    '-1',             // 28. Pivot mode
    '0.0000',         // 29. Pivot position
    '-1',             // 30. Alpha ctrl number
    '0',              // 31. Alpha ctrl channel
    '1',              // 32. OkTranspose
    '1',              // 33. OkArticulate
    '1',              // 34. OkVolume
    '1',              // 35. OkPan
    '1',              // 36. OkMap
    '1',              // 37. OkVelocity
    '0',              // 38. PreRoll
    '0',              // 39. PostRoll
    '0',              // 40. PreRoll mode
    '0',              // 41. PostRoll mode
    '-2',             // 42. Period mode
    '0',              // 43. Before period
    '0',              // 44. Force integer period
    '0',              // 45. Discard note offs
    '-1',             // 46. Strike again
    '-1',             // 47. Csound assigned instr
    '0',              // 48. Csound instr
    '1000000',        // 49. Tpict
    '65535',          // 50. Color R (deprecated)
    '65535',          // 51. Color G
    '65535',          // 52. Color B
  ];
}

/**
 * Empty Csound score section.
 */
function csoundSection() {
  return [
    '_beginCsoundScore_',
    '<HTML></HTML>',
    '_endCsoundScore_',
  ];
}

/**
 * MIDI section: NoteOn at t=0, NoteOff at t=duration.
 * Each value = time_ms * 256 + midi_byte (Euclidean encoding)
 * 6 values = 2 events × 3 bytes (status, note, velocity)
 * @param {number} duration - duration in ms
 */
function midiSection(duration) {
  // Encoding: k = time * 256 + byte
  // NoteOn(60, vel=100) at t=0
  const on1 = 0 * 256 + 144;     // t=0, status=0x90 (NoteOn ch0)
  const on2 = 0 * 256 + 60;      // t=0, note=60 (C4)
  const on3 = 0 * 256 + 100;     // t=0, velocity=100

  // NoteOff(60, vel=0) at t=duration
  const off1 = duration * 256 + 128;  // t=duration, status=0x80 (NoteOff ch0)
  const off2 = duration * 256 + 60;   // t=duration, note=60
  const off3 = duration * 256 + 0;    // t=duration, velocity=0

  return [
    '6',           // MIDI size (6 encoded values)
    String(on1),   // 144
    String(on2),   // 60
    String(on3),   // 100
    String(off1),  // 256128
    String(off2),  // 256060
    String(off3),  // 256000
  ];
}
