// Auto-generated by syntaxe-bundle.mjs — do not edit
// LA PORTE DU SCHÉMA DE SYNTAXE — ce que le langage EST : ses mots et les valeurs de
// ses directives. Artefact VERSIONNÉ, lisible par `git show` sans construction.

const SYNTAXE = {
 "_source": "BPscript/schema-syntaxe/language.json",
 "syntaxWords": {
  "->": {
   "kind": "operator",
   "description": "Règle de production : le membre gauche est réécrit en membre droit (défaut gauche→droite)",
   "syntax": "LHS -> RHS"
  },
  "<-": {
   "kind": "operator",
   "description": "Règle d'analyse : la séquence droite est réduite au symbole gauche (droite→gauche)",
   "syntax": "LHS <- RHS"
  },
  "<>": {
   "kind": "operator",
   "description": "Règle bidirectionnelle : production ET analyse",
   "syntax": "LHS <> RHS"
  }
 },
 "directiveValues": {
  "mode": {
   "description": "Mode de dérivation du sous-grammaire suivant",
   "values": [
    {
     "name": "ord",
     "description": "Ordonné — règles appliquées séquentiellement (défaut)"
    },
    {
     "name": "rnd",
     "description": "Aléatoire — sélection pondérée"
    },
    {
     "name": "lin",
     "description": "Linéaire — bouclage cyclique"
    },
    {
     "name": "sub",
     "description": "Substitution — remplacement simultané de toutes les occurrences"
    },
    {
     "name": "sub1",
     "description": "Substitution du premier — occurrence la plus à gauche seulement"
    },
    {
     "name": "tem",
     "description": "Template — appariement structurel"
    },
    {
     "name": "poslong",
     "description": "Positional longest — plus longue correspondance d'abord"
    }
   ]
  },
  "scan": {
   "description": "Placement de la règle candidate dans le contexte",
   "values": [
    {
     "name": "left",
     "description": "Argument gauche"
    },
    {
     "name": "right",
     "description": "Argument droit"
    },
    {
     "name": "rnd",
     "description": "Aléatoire"
    }
   ]
  }
 },
 "grammarWords": {
  "description": "Les mots avec lesquels on écrit la STRUCTURE — la grammaire, qu'un auteur ne peut jamais ombrer. Un PLANCHER : ce qui n'a pas su être établi ne compte pas comme une absence. Dissous du schéma de `core` le 2026-09-03.",
  "qualite": "plancher",
  "mots": [
   "actor",
   "core",
   "def",
   "in",
   "init",
   "mode",
   "out",
   "seed",
   "terminal"
  ],
  "syntaxe": {
   "description": "La FORME que chaque mot admet, pour que son refus donne une réécriture au lieu de constater. Un mot du langage écrit autrement — qualifié par un point qu'il n'admet pas, par exemple — est refusé avec la ligne qu'il fallait écrire.",
   "actor": "actor <nom>",
   "core": "core",
   "def": "def <nom> <corps>",
   "in": "in.<canal> <rôle>",
   "init": "init",
   "mode": "mode:<mode>",
   "out": "out.<canal>",
   "seed": "seed:<N>",
   "terminal": "terminal <nom> <corps>"
  }
 },
 "bracketRewrites": {
  "description": "Les réglages que le CROCHET a portés et qui s'écrivent en PARENTHÈSES depuis la décision du 2026-08-02. Le compilateur les comprend lui-même : écrits entre crochets, ils sont refusés AVEC leur réécriture, au lieu de tomber sur « clé inconnue ». Une pierre tombale de graphie, donc du LANGAGE — elle a quitté le schéma de `core` avec lui le 2026-09-03.",
  "mots": [
   "scan",
   "weight",
   "on_fail",
   "meter",
   "rotate",
   "legato",
   "staccato"
  ]
 },
 "actorKeyRewrites": {
  "description": "Les mots qu'un acteur a portés comme clés et qui n'en sont plus : `sound` et `sounds` (un prototype d'objet sonore vit en librairie), `voice` (une voix s'attache au terminal). Écrits sur un acteur, ils sont refusés AVEC ce qui les remplace, au lieu de tomber dans la lecture générique d'une affectation. Une pierre tombale de graphie, donc du LANGAGE — elle a quitté le schéma de `core` avec lui le 2026-09-03.",
  "mots": [
   "sound",
   "sounds",
   "voice"
  ]
 }
};

export { SYNTAXE };
