// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Scene = 1,
  LineComment = 2,
  Separator = 3,
  Directive = 4,
  RulePrefix = 5,
  Arrow = 6,
  BacktickCode = 7,
  Variable = 8,
  FlagExpr = 9,
  Weight = 10,
  TypeKeyword = 11,
  LambdaKeyword = 12,
  Number = 13,
  Symbol = 14,
  Newline = 15,
  Operator = 16
